MicrosoftDocs/iis-docs

iis/get-started/whats-new-in-iis-10/new-features-introduced-in-iis-10.md
* Changed IIS.Administration to IIS Administration
* Reworded the section
* Removed preview label
=> Changes to IIS Administration in new IIS 10 features.

iis/TOC.md, iis/get-started/whats-new-in-iis-10/new-features-introduced-in-iis-10.md, iis/get-started/whats-new-in-iis-10/thread-pool-ideal-cpu-numa-optimization.md
Add introduction to IIS thread pool idea CPU optimization to the main IIS 10.0 new feature article.
=> IIS thread pool ideal CPU optimization for NUMA hardware

iis/TOC.md, iis/web-dev-reference/index.md, iis/web-dev-reference/server-variables.md
=> Add Server Variables doc

iis/TOC.md, iis/extensions/cors-module/cors-module-configuration-reference.md, iis/extensions/cors-module/cors-module-configuration-reference/samples/sample1.cs, iis/extensions/cors-module/cors-module-configuration-reference/samples/sample2.cs, iis/extensions/cors-module/cors-module-configuration-reference/samples/sample3.cmd, iis/extensions/cors-module/cors-module-configuration-reference/samples/sample4.cmd
https://github.com/MicrosoftDocs/iis-docs/issues/77
=> Add CORS configuration reference documentation

iis/install/installing-iis-7/using-unattended-setup-to-install-iis/samples/sample5.xml
Fixes a spelling mistake <ssemblyIdentity /> to <AssemblyIdentity />
=> Spelling fix

iis/extensions/cors-module/cors-module-configuration-reference.md
@jimmyca15 @bariscaglar  @bangbingsyb  New PR: Updated after Jimmy's feedbacks.
=> Updated after feedkbacks

iis/web-hosting/installing-infrastructure-components/preparation-activities-for-wds.md
First step towards deprecating this article
=> Remove broken links

iis/get-started/whats-new-in-iis-10/iisadministration-powershell-cmdlets.md
@bariscaglar Would you review this doc change? 
This is for #105.
=> Update to add IISAdministration powershell gallery information

iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-1709-hsts/samples/sample-httpredirect-https-site.xml
Based on the comment under: https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-1709-hsts
=> Fix a typo in the HSTS config sample

iis/TOC.md, iis/install/installing-iis-7/iis-features-and-vista-editions.md
addresses [https://github.com/MicrosoftDocs/iis-docs/issues/9](https://github.com/MicrosoftDocs/iis-docs/issues/9)
=> Adding IIS Administration link to TOC

iis/application-frameworks/scenario-build-a-php-website-on-iis/configuring-step-1-install-iis-and-php.md, iis/application-frameworks/scenario-build-a-php-website-on-iis/planning-step-1-plan-iis-web-server-and-php-installation.md
The initial PR fixed two links.
=> [WIP] Attempted to update PHP WinCache documentation.

iis/get-started/whats-new-in-iis-10/wildcard-host-header-support.md
Fixes https://github.com/aspnet/Docs-Private/issues/6
Add a warning message to coincide with the release of the server host configuration MSRC: https://github.com/aspnet/Announcements/issues/295
=> Add server host configuration warning

iis/manage/configuring-security/application-pool-identities-and-sql-server-express.md
"develoer" -> "developer"
_(I did nothing with the last paragraph; not sure why it's showing as changed)_
=> Minor typo fix

iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe.md
=> Remove unnecessary backslash

iis/extensions/iis-compression/iis-compression-overview.md
=> Updated iis compression doc based on review.

iis/application-frameworks/building-and-running-aspnet-applications/how-to-take-advantage-of-the-iis-integrated-pipeline.md
remove invalid slashed in path
=> remove invalid slashes

iis/publish/using-web-deploy/web-deploy-automatic-backups/samples/sample4.ps1
[Internal review URL](https://review.docs.microsoft.com/en-us/IIS/publish/using-web-deploy/web-deploy-automatic-backups?branch=pr-en-us-169)
=> Add missing line breaks to Configure-Backups samples

iis/application-frameworks/building-and-running-aspnet-applications/how-to-take-advantage-of-the-iis-integrated-pipeline/samples/sample4.xml
Without the password node the app crashes with a null exception when the user tries to log in.
=> Add password node to first user

iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe/samples/sample18.cmd, iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe/samples/sample19.cmd
=> Fixed paths

iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference.md
=> Update url-rewrite-module-configuration-reference.md - StopProcessing 

iis/web-hosting/microsoft-web-farm-framework-20-for-iis-7/system-and-platform-requirements-for-the-web-farm-framework-20-for-iis.md
=> typo: Double word "an"

iis/TOC.yml
the extensions link in the toc was pointing to a random extension library
=> fixed extensions link in toc

iis/manage/configuring-security/application-pool-identities.md
Add some spacing around the screenshots to improve the layout.
=> Add some spacing

iis/configuration/system.webServer/security/authentication/windowsAuthentication/extendedProtection/spn.md
=> Fix misspellings of principle to principal

iis/application-frameworks/building-and-running-aspnet-applications/how-to-capture-aspnet-page-trace-events-in-iis-tracing.md, iis/application-frameworks/building-and-running-aspnet-applications/wildcard-script-mapping-and-iis-integrated-pipeline.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/gallery2-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/phplist-on-iis.md, iis/application-frameworks/install-and-configure-php-on-iis/enable-fastcgi-support-in-iis-7-on-windows-server-2008-windows-server-2008-r2-windows-vista-or-windows-7.md, iis/application-frameworks/install-and-configure-php-on-iis/install-and-configure-mysql-for-php-applications-on-iis-7-and-above.md, iis/application-frameworks/install-and-configure-php-on-iis/install-php-and-fastcgi-support-on-server-core.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-php-with-configuration-settings.md, iis/application-frameworks/install-and-configure-php-on-iis/setting-up-a-database-for-a-php-application-on-iis.md, iis/application-frameworks/install-and-configure-php-on-iis/use-the-windows-cache-extension-for-php.md
Preparing for Markdig migration
Also did a few style changes and link updates and typo fixes along the way.
=> markdig fixes - Part 1

iis/application-frameworks/install-and-configure-php-applications-on-iis/using-fastcgi-to-host-php-applications-on-iis-60.md, iis/application-frameworks/install-and-configure-php-on-iis/configuring-the-fastcgi-extension-for-iis-60.md, iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/configuring-step-3-configure-data-source-settings.md, iis/configuration/system.applicationHost/sites/site/ftpServer/fileHandling.md, iis/configuration/system.applicationHost/sites/site/hsts.md, iis/configuration/system.applicationHost/sites/site/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/fileHandling.md, iis/extensions/url-rewrite-module/importing-apache-modrewrite-rules.md, iis/extensions/using-iis-express/running-iis-express-from-the-command-line.md, iis/extensions/using-iis-express/using-the-windows-system-tray-to-manage-websites-and-applications.md
Preparing for Markdig migration
Also did a few style changes and link updates and typo fixes along the way.
=> markdig fixes - Part 2

iis/configuration/system.webServer/security/requestFiltering/index.md, iis/configuration/system.webServer/security/requestFiltering/requestLimits/headerLimits/add.md, iis/configuration/system.webServer/security/requestFiltering/requestLimits/headerLimits/index.md, iis/configuration/system.webServer/security/requestFiltering/requestLimits/index.md, iis/manage/configuring-security/configure-request-filtering-in-iis.md, iis/manage/configuring-security/use-request-filtering.md, iis/troubleshoot/diagnosing-http-errors/how-to-use-http-detailed-errors-in-iis.md
=> Fixed doc issues for status code

iis/get-started/planning-for-security/how-to-use-locking-in-iis-configuration/samples/sample7.xml, iis/get-started/planning-for-security/how-to-use-locking-in-iis-configuration/samples/sample9.xml
=> Correct typo in code

iis/get-started/introduction-to-iis/iis-modules-overview/samples/sample1.xml
The XML file was invalid due to missing spaces.
=> Added necessary spaces.

.markdownlint.json, iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy.md
Inconsistent indentation for list items at the same level
=> fix: MD005/list-indent

iis/extensions/url-rewrite-module/using-rewrite-maps-in-url-rewrite-module.md
Matching the text with the sample code.
=> Fix typo in url attribute

.markdownlint.json, iis/application-frameworks/building-and-running-aspnet-applications/how-to-use-the-sample-read-only-xml-membership-and-role-providers-with-iis.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-provider-that-prevents-leeching.md, iis/manage/working-with-server-core/iis-70-on-server-core.md, iis/troubleshoot/diagnosing-http-errors/troubleshooting-http-400-errors-in-iis.md, iis/web-hosting/installing-infrastructure-components/dhcp-server.md
Lists should be surrounded by blank lines
=> fix: MD032/blanks-around-lists

.markdownlint.json, iis/extensions/cors-module/cors-module-configuration-reference.md
Spaces inside emphasis markers
=> fix: MD037/no-space-in-emphasis

iis/web-development-reference/native-code-api-reference/hosted-web-core-api-reference.md
- First entry was repeated, but wrong for description
- Added link for second ref
=> fix: hosted-web-core-api-reference.md

.markdownlint.json, iis/application-frameworks/building-and-running-aspnet-applications/how-to-capture-aspnet-page-trace-events-in-iis-tracing.md, iis/application-frameworks/building-and-running-aspnet-applications/how-to-use-the-sample-read-only-xml-membership-and-role-providers-with-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/install-drupal-on-iis.md, iis/application-frameworks/install-and-configure-php-on-iis/configure-smtp-e-mail-in-iis-7-and-above.md, iis/application-frameworks/running-php-applications-on-iis/configure-php-process-recycling-behavior.md, iis/contribute.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-authentication-provider.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-home-directory-provider.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-logging-provider.md, iis/develop/installingpublishing-apps-with-webmatrix/acquia-drupal-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/sitefinity-community-edition-faq.md, iis/develop/runtime-extensibility/developing-a-module-using-net.md, iis/develop/windows-web-application-gallery/reference-for-the-web-application-package.md, iis/extensions/database-manager/working-with-stored-procedures.md, iis/extensions/database-manager/working-with-views.md, iis/install/installing-iis-7/using-unattended-setup-to-install-iis.md, iis/publish/using-web-deploy/parameterization-improvements-in-web-deploy-v3.md, iis/publish/using-webdav/how-to-migrate-fpse-sites-to-webdav.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/application-request-routing-arr-20-for-shared-hosting.md, iis/web-hosting/verifying-the-deployment/verifying-the-developer-experience-php.md
Replace hard tabs and some minor escaping issues
=> fix: MD010/no-hard-tabs

iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage.md
Tool was moved from: http://www.erezbenari.com/IISLogCleaner.exe to http://www.erezbenari.com/apps/IISLogCleaner.exe
Landing Page URL: http://www.erezbenari.com/apps/includes/apps/iislogcleaner.html
=> Updating URL to IISLogCleaner.exe

iis/get-started/introduction-to-iis/iis-modules-overview/samples/sample2.xml
=> format & typo

iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-not-installed-by-default-on-iis.md
- adds image alt text
- also adds space where missing in some headings
fixes #507
=> Add missing alt text and some space in headings where necessary

iis/application-frameworks/install-and-configure-php-on-iis/using-php-manager-for-iis-to-setup-and-configure-php.md, iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-not-installed-by-default-on-iis.md, iis/configuration/system.webServer/httpErrors/error.md, iis/configuration/system.webServer/security/requestFiltering/fileExtensions/index/samples/sample2.cmd, iis/get-started/introduction-to-iis/iis-modules-overview/samples/sample2.xml, iis/get-started/introduction-to-iis/iis-modules-overview/samples/sample3.xml, iis/get-started/whats-new-in-iis-8/iis-80-application-initialization.md, iis/manage/managing-performance-settings/walkthrough-iis-output-caching/samples/sample5.cmd, iis/publish/using-web-deploy/web-deploy-automatic-backups/samples/sample2.cmd
It seems the last merge was squashed. Merge to live needs to just be merged.
=> Update live with current master

iis/develop/windows-web-application-gallery/azure-app-gallery-faq.md, iis/develop/windows-web-application-gallery/blogengine-net-sample-files.md, iis/develop/windows-web-application-gallery/database-notes-for-packaging-applications-for-use-with-the-web-application-gallery.md, iis/develop/windows-web-application-gallery/frequently-asked-questions.md, iis/develop/windows-web-application-gallery/gallery-server-pro-sample-files.md, iis/develop/windows-web-application-gallery/how-to-create-an-app-package-supporting-both-sql-server-and-mysql.md, iis/develop/windows-web-application-gallery/integrate-the-windows-web-application-gallery-into-a-control-panel.md, iis/develop/windows-web-application-gallery/introducing-the-windows-web-application-gallery.md, iis/develop/windows-web-application-gallery/joomla-sample-files.md, iis/develop/windows-web-application-gallery/mediawiki-sample-files.md, iis/develop/windows-web-application-gallery/package-an-application-for-the-windows-web-application-gallery.md, iis/develop/windows-web-application-gallery/reference-for-the-web-application-package.md, iis/develop/windows-web-application-gallery/testing-a-web-application-zip-package-for-inclusion-with-the-web-application-gallery.md, iis/develop/windows-web-application-gallery/umbraco-cms-sample-files.md, iis/develop/windows-web-application-gallery/using-the-microsoft-web-platform-installer-badge.md, iis/develop/windows-web-application-gallery/windows-web-application-gallery-known-issues.md, iis/develop/windows-web-application-gallery/windows-web-application-gallery-link-addition-process-walkthrough.md, iis/develop/windows-web-application-gallery/windows-web-application-gallery-principles.md, iis/develop/windows-web-application-gallery/wordpress-sample-files.md
Since the Windows Web Application Gallery is being retired, we need to add verbiage to that affect to all of its doc pages.
=> Add a blurb about the retirement of the WWAG

.github/workflows/check-for-build-warnings.yml
=> Exclude status checker from running on live branch

iis/extensions/advanced-logging-module/advanced-logging-for-iis-client-logging.md, iis/extensions/advanced-logging-module/advanced-logging-for-iis-custom-logging.md, iis/extensions/advanced-logging-module/advanced-logging-for-iis-real-time-logging.md, iis/extensions/advanced-logging-module/advanced-logging-readme.md, iis/extensions/url-rewrite-module/using-failed-request-tracing-to-trace-rewrite-rules.md
@John-Hart if you can approve I'll merge to live
=> Merge to live

iis/publish/using-webdav/using-the-webdav-redirector.md
Added troubleshooting steps around using webdav client with a non-Windows webdav server.
=> request from CSS to update webdav client docs

iis/configuration/system.ftpServer/security/authentication/denyByFailure/samples/sample1.xml, iis/configuration/system.ftpServer/security/authentication/index/samples/sample1.xml
I fixed a typo .
iis manager build configuration ：
https://github.com/vchy1997/vchy1997.issues/blob/646b76096793ccb7e3e122d64f69cd977cf3ec0c/iis-docs/%23580/applicationHost.config#L760-L762
use 【Authentication】 prompt：
https://github.com/vchy1997/vchy1997.issues/blob/master/iis-docs/%23580/%23580_Error.png
=> fix typo #580

iis/develop/installingpublishing-apps-with-webmatrix/blogenginenet-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/dasblog-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/gallery-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/gallery-server-pro-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/kooboo-cms-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/mojoportal-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/moodle-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/my-web-pages-starter-kit-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/nopcommerce-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/resourceblendernet-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/screwturn-wiki-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/silverstripe-cms-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/sitefinity-community-edition-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/subtext-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/sugarcrm-faq.yml, iis/develop/installingpublishing-apps-with-webmatrix/umbraco-cms-faq.yml, iis/develop/windows-web-application-gallery/azure-app-gallery-faq.yml, iis/develop/windows-web-application-gallery/frequently-asked-questions.yml, iis/extensions/introduction-to-iis-express/iis-express-faq.yml, iis/extensions/working-with-urlscan/urlscan-faq.yml, iis/web-hosting/frequently-asked-questions-faq/general-iis7-questions.yml, iis/web-hosting/frequently-asked-questions-faq/logging-and-auditing-questions.yml, iis/web-hosting/frequently-asked-questions-faq/net-questions.yml, iis/web-hosting/frequently-asked-questions-faq/security-questions.yml, iis/web-hosting/frequently-asked-questions-faq/tools-and-utilities-questions.yml, iis/web-hosting/frequently-asked-questions-faq/top-10-changes-in-iis7.yml
Set ms.topic: faq where YamlMime:FAQ
Note the following:
- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that …
=> Set ms.topic: faq where YamlMime:FAQ

iis/publish/using-webdav/using-the-webdav-redirector.md, iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-addrawcollectionelement-method.md, iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-interface.md
This PR fixes 7 disallowed HTML issues.
Links to preview URLs:
[inativeconfigurationelementcollection-interface.md](https://review.docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-interface?branch=pr-en-us-627)
[inativeconfigurationelementcollection-addrawcollectionelement-method.md](https://review.docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-addrawcollectionelement-method?branch=pr-en-us-627)
[using-the-webdav-redirector.md](https://review.docs.microsoft.com/en-us/iis/publish/using-webdav/using-the-webdav-redirector?branch=pr-en-us-627)
=> [bulk]Validation: Fix disallowed html (iis-docs)

iis/application-frameworks/install-and-configure-php-applications-on-iis/mediawiki-on-iis.md
* MediaWiki is the software, Wikimedia is the movement...
* Add alternate text to images
=> Update MediaWiki on IIS pages

iis/publish/troubleshooting-web-deploy/web-deploy-error-codes.md
new solution for ERROR_CERTIFICATE_VALIDATION_FAILED
=> ERROR_CERTIFICATE_VALIDATION_FAILED

iis/application-frameworks/install-and-configure-php-on-iis/install-and-configure-mysql-for-php-applications-on-iis-7-and-above.md, iis/application-frameworks/install-and-configure-php-on-iis/install-the-sql-server-driver-for-php.md, iis/configuration/system.webServer/webSocket.md, iis/develop/extending-the-management-ui/overview-of-mwa-and-mwm-for-iis.md, iis/install/installing-iis-7/installing-iis-from-the-command-line.md
This PR addresses missing image alternate text and fixes absolute links.
=> Add missing alt text

iis/extensions/smooth-streaming-client/iadaptivesource-adaptivesourcestatusupdatedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesource-interface.md, iis/extensions/smooth-streaming-client/iadaptivesource-manifest-property.md, iis/extensions/smooth-streaming-client/iadaptivesource-manifestreadyevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesource-uri-property.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourceclosedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourcefailedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourcemanagerfailedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourceopenedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesources-property.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourcestatusupdatedevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-interface.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-manifestreadyevent-event.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-sendextendedcommand-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setbufferdelay-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setdownloaderplugin-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setlivebackoffsec-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setlivebeginoffsetsec-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setplaybackoffsetsec-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanagerstatics-getdefault-method.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanagerstatics-interface.md, iis/extensions/smooth-streaming-client/ichunkiter-interface.md, iis/extensions/smooth-streaming-client/ichunkiter-movenext-method.md, iis/extensions/smooth-streaming-client/ichunkiter-moveprev-method.md, iis/extensions/smooth-streaming-client/idownloaderplugin-interface.md, iis/extensions/smooth-streaming-client/idownloaderplugin-requestasync-method.md, iis/extensions/smooth-streaming-client/idownloaderplugin-responsedata-method.md, iis/extensions/smooth-streaming-client/ihttpcookie-expiretime-property.md, iis/extensions/smooth-streaming-client/ihttpcookie-flags-property.md, iis/extensions/smooth-streaming-client/ihttpcookie-interface.md
=> Message fixes | Validation issues | 5 (BULK)

iis/application-frameworks/install-and-configure-php-on-iis/using-php-manager-for-iis-to-setup-and-configure-php.md, iis/develop/windows-web-application-gallery/using-the-microsoft-web-platform-installer-badge.md, iis/extensions/configuring-application-request-routing-arr/use-scavengeexe-tool-to-delete-cached-content-from-secondary-cache-drive.md, iis/media/web-playlists/web-playlists-for-iis-configuration.md, iis/publish/deploying-application-packages/dotnetnuke.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/configuring-share-and-ntfs-permissions.md, iis/web-hosting/microsoft-web-farm-framework-20-for-iis-7/setting-up-a-server-farm-with-the-web-farm-framework-20-for-iis.md
This PR fixes 6 disallowed domain, 11 external image, and 32 missing alt text issues.
=> [Bulk] Validation: Fix domain, external image site, and alt text issues

iis/configuration/system.applicationHost/sites/site/ftpServer/Stop.md, iis/configuration/system.applicationHost/sites/site/logFile/customFields/add.md, iis/develop/extending-the-management-ui/understanding-ui-extension-authoring.md, iis/develop/runtime-extensibility/an-end-to-end-extensibility-example-for-iis-developers.md, iis/develop/runtime-extensibility/sample-web-analytics-tracking-module.md, iis/manage/managing-your-configuration-settings/shared-configuration_264.md, iis/media/web-playlists/using-windows-media-player-playlist-files-in-web-playlists.md, iis/publish/using-web-deploy/dbdacfx-provider-for-incremental-database-publishing.md
This PR fixes 53 Missing Alt Text issues.
=> [Bulk] Validation: Fix Missing Alt Text 3

iis/extensions/smooth-streaming-client/ihttpcookie-name-property.md, iis/extensions/smooth-streaming-client/ihttpcookie-p3ppolicy-property.md, iis/extensions/smooth-streaming-client/ihttpcookie-uri-property.md, iis/extensions/smooth-streaming-client/ihttpcookie-value-property.md, iis/extensions/smooth-streaming-client/imanifest-interface.md, iis/extensions/smooth-streaming-client/imanifeststream-availabletracks-property.md, iis/extensions/smooth-streaming-client/imanifeststream-childstreams-property.md, iis/extensions/smooth-streaming-client/imanifeststream-displayheight-property.md, iis/extensions/smooth-streaming-client/imanifeststream-displaywidth-property.md, iis/extensions/smooth-streaming-client/imanifeststream-downloadfragmentasync-method.md, iis/extensions/smooth-streaming-client/imanifeststream-firstincurrentchunklist-property.md, iis/extensions/smooth-streaming-client/imanifeststream-getattribute-method.md, iis/extensions/smooth-streaming-client/imanifeststream-getchunkinfoasync-method.md, iis/extensions/smooth-streaming-client/imanifeststream-getiterator-method.md, iis/extensions/smooth-streaming-client/imanifeststream-interface.md, iis/extensions/smooth-streaming-client/imanifeststream-language-property.md, iis/extensions/smooth-streaming-client/imanifeststream-lastincurrentchunklist-property.md, iis/extensions/smooth-streaming-client/imanifeststream-maxheight-property.md, iis/extensions/smooth-streaming-client/imanifeststream-maxwidth-property.md, iis/extensions/smooth-streaming-client/imanifeststream-name-property.md, iis/extensions/smooth-streaming-client/imanifeststream-parentstream-property.md, iis/extensions/smooth-streaming-client/imanifeststream-restricttracks-method.md, iis/extensions/smooth-streaming-client/imanifeststream-selectedtracks-property.md, iis/extensions/smooth-streaming-client/imanifeststream-selecttracks-method.md, iis/extensions/smooth-streaming-client/imanifeststream-subtype-property.md, iis/extensions/smooth-streaming-client/imanifeststream-timescale-property.md, iis/extensions/smooth-streaming-client/imanifeststream-type-property.md, iis/extensions/smooth-streaming-client/imanifeststream-url-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-audiotag-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface.md
=> Message fixes | Validation issues | 6 (BULK)

iis/extensions/smooth-streaming-client/imanifesttrack-interface-bitrate-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-codecprivatedata-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-customattributenames-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-fourcc-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-getattribute-method.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-getcustomattribute-method.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-hardwareprofile-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-maxheight-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-maxwidth-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-naunitlength-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-nominalbitrate-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-stream-property.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-trackindex-property.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-interface-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-interface-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/istreamchangedresult-action-property.md, iis/extensions/smooth-streaming-client/istreamchangedresult-interface.md, iis/extensions/smooth-streaming-client/istreamchangedresult-resultcode-property.md, iis/extensions/smooth-streaming-client/istreamchangedresult-stream-property.md, iis/extensions/smooth-streaming-client/manifest-availablestreams-property.md, iis/extensions/smooth-streaming-client/manifest-class.md, iis/extensions/smooth-streaming-client/manifest-duration-property.md, iis/extensions/smooth-streaming-client/manifest-dvrwindowlength-property.md, iis/extensions/smooth-streaming-client/manifest-getattribute-method.md, iis/extensions/smooth-streaming-client/manifestinfo-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifestinfo-events-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-events-microsoft-web-media-smoothstreaming_1.md
=> Message fixes | Validation issues | 7 (BULK)

iis/extensions/smooth-streaming-client/manifest-islive-property.md, iis/extensions/smooth-streaming-client/manifest-lookaheadcount-property.md, iis/extensions/smooth-streaming-client/manifest-majorversion-property.md, iis/extensions/smooth-streaming-client/manifest-minorversion-property.md, iis/extensions/smooth-streaming-client/manifest-selectedstreams-property.md, iis/extensions/smooth-streaming-client/manifest-selectstreamsasync-method.md, iis/extensions/smooth-streaming-client/manifest-starttime-property.md, iis/extensions/smooth-streaming-client/manifestinfo-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifestinfo-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifestreadyeventargs-adaptivesource-property.md, iis/extensions/smooth-streaming-client/manifestreadyeventargs-class.md, iis/extensions/smooth-streaming-client/manifestreadyeventhandler-delegate.md, iis/extensions/smooth-streaming-client/manifeststream-availabletracks-property.md, iis/extensions/smooth-streaming-client/manifeststream-childstreams-property.md, iis/extensions/smooth-streaming-client/manifeststream-class.md, iis/extensions/smooth-streaming-client/manifeststream-displayheight-property.md, iis/extensions/smooth-streaming-client/manifeststream-displaywidth-property.md, iis/extensions/smooth-streaming-client/manifeststream-downloadfragmentasync-method.md, iis/extensions/smooth-streaming-client/manifeststream-firstincurrentchunklist-property.md, iis/extensions/smooth-streaming-client/manifeststream-getattribute-method.md, iis/extensions/smooth-streaming-client/manifeststream-getchunkinfoasync-method.md, iis/extensions/smooth-streaming-client/manifeststream-getiterator-method.md, iis/extensions/smooth-streaming-client/manifeststream-language-property.md, iis/extensions/smooth-streaming-client/manifeststream-lastincurrentchunklist-property.md, iis/extensions/smooth-streaming-client/manifeststream-maxheight-property.md, iis/extensions/smooth-streaming-client/manifeststream-maxwidth-property.md, iis/extensions/smooth-streaming-client/manifeststream-name-property.md, iis/extensions/smooth-streaming-client/manifeststream-restricttracks-method.md
=> Message fixes | Validation issues | 8 (BULK)

iis/configuration/system.applicationHost/sites/site/ftpServer/connections.md, iis/configuration/system.applicationHost/sites/siteDefaults/index.md, iis/configuration/system.webServer/httpCompression/staticTypes/add.md, iis/configuration/system.webServer/management/authorization/authorizationRules/scope/index.md, iis/configuration/system.webServer/management/authorization/index.md, iis/configuration/system.webServer/security/requestFiltering/filteringRules/filteringRule/denyStrings/add.md, iis/configuration/system.webServer/tracing/traceFailedRequests/index.md, iis/get-started/whats-new-in-iis-8/iis-80-dynamic-ip-address-restrictions.md, iis/publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7.md, iis/troubleshoot/using-failed-request-tracing/troubleshooting-failed-requests-using-tracing-in-iis.md
This PR fixes 68 missing alt text issues.
=> [Bulk] Validation: Fix missing alt text 3/15

iis/extensions/transform-manager/jobdetails-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-fields-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-dispose-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-events-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-fields-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmetadata-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmetadata-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmetadata-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-addconfigurationmessage-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-constructor-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-addconfigurationmessage-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-constructor-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-dispose-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/logger-class-microsoft-web-media-transformmanager.md
=> Message fixes | Validation issues | 16 (BULK) 

iis/configuration/system.applicationHost/sites/site/ftpServer/customFeatures/providers/add.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/customAuthentication/providers/add.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/commandFiltering/add.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/sslClientCertificates.md, iis/configuration/system.webServer/asp/session.md, iis/configuration/system.webServer/security/requestFiltering/filteringRules/filteringRule/appliesTo/index.md, iis/configuration/system.webServer/tracing/traceProviderDefinitions/add/areas/index.md, iis/configuration/system.webServer/webdav/globalSettings/lockStores/add.md, iis/get-started/whats-new-in-iis-10/http2-on-iis.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/offline-files-for-shared-configuration.md, iis/web-hosting/installing-infrastructure-components/system-center-solutions-vmm-amp-scom.md
This PR fixes 59 missing Alt Text issues.
=> {Bulk]Validation-Missing-Alttext

iis/extensions/transform-manager/taskdetails-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdetails-structure-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-dispose-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-findelement-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/workqueue-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/workqueue-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/workqueue-properties-microsoft-web-media-transformmanager.md, iis/extensions/troubleshooting-application-request-routing/troubleshooting-cache-items-arr-v2.md
=> Message fixes | Validation issues | 18 (BULK)

iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/basicAuthentication.md, iis/configuration/system.webServer/security/authorization/add.md, iis/configuration/system.webServer/security/requestFiltering/fileExtensions/add.md, iis/configuration/system.webServer/webdav/authoringRules/add.md, iis/develop/windows-web-application-gallery/using-the-microsoft-web-platform-installer-badge.md, iis/manage/provisioning-and-managing-iis/iis-management-and-administration.md, iis/publish/deploying-application-packages/deploying-drupal-via-packages-in-a-hosting-environment.md, iis/web-hosting/hosting-the-microsoft-web-platform-on-amazon-ec2/amazon-ec2-microsoft-web-platform-images-full-web-server-development-stack.md, iis/web-hosting/web-server-for-shared-hosting/url-rewrite-for-hosting-providers.md
This PR fixes 84 missing alt text issues.
=> [Bulk] Validation: Fix missing alt text 3/17

iis/configuration/system.applicationHost/sites/site/ftpServer/sessions/session.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/customFeatures/providers/add.md, iis/configuration/system.ftpServer/security/authentication/index.md, iis/configuration/system.webServer/security/authentication/clientCertificateMappingAuthentication.md, iis/configuration/system.webServer/security/authentication/iisClientCertificateMappingAuthentication/manyToOneMappings/add/index.md, iis/configuration/system.webServer/tracing/traceFailedRequests/add/failureDefinitions.md, iis/configuration/system.webServer/webdav/authoring/locks.md, iis/publish/using-webdav/using-the-webdav-redirector.md, iis/web-hosting/joining-the-web-hosting-gallery/how-webmatrix-verification-works.md
This PR has 72 missing alt text fixes.
=> [Bulk]Validation-Missing-Alttext2

iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/customAuthentication/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/logFile/index.md, iis/configuration/system.ftpServer/security/ipSecurity/index.md, iis/configuration/system.webServer/security/dynamicIpSecurity/index.md, iis/configuration/system.webServer/webdav/authoringRules/index.md, iis/develop/using-webmatrix/analyze-requests-to-your-website.md, iis/publish/using-the-ftp-service/using-ftp-over-ssl-in-iis-7.md, iis/troubleshoot/performance-issues/troubleshooting-high-cpu-in-an-iis-7x-application-pool.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/windows-communication-framework-wcf.md, iis/web-hosting/installing-infrastructure-components/dns-server.md, iis/web-hosting/microsoft-web-farm-framework-20-for-iis-7/web-farm-framework-20-for-iis-cmdlets-for-windows-powershell.md
This PR fixes 74 missing alt text issues.
=> [Bulk] Validation: Fix missing alt text 3/18

iis/application-frameworks/install-and-configure-php-applications-on-iis/cubecart-on-iis.md, iis/configuration/system.webServer/directoryBrowse.md, iis/extensions/advanced-logging-module/advanced-logging-for-iis-custom-logging.md, iis/extensions/configuring-application-request-routing-arr/configure-3-tier-deployment-architecture-using-application-request-routing.md, iis/extensions/planning-for-arr/overview-of-shared-hosting-deployment-using-application-request-routing-20.md
=> Alt Text Inclusions

iis/configuration/system.applicationHost/applicationPools/add/failure.md, iis/configuration/system.applicationHost/customMetadata/index.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/clientCertAuthentication.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/customAuthorization/provider.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/sslClientCertificates.md, iis/configuration/system.ftpServer/security/requestFiltering/fileExtensions/index.md, iis/configuration/system.ftpServer/security/requestFiltering/requestLimits.md, iis/configuration/system.ftpServer/serverRuntime/hostNameSupport.md, iis/configuration/system.webServer/security/authentication/digestAuthentication.md, iis/configuration/system.webServer/security/authorization/index.md, iis/configuration/system.webServer/security/requestFiltering/hiddenSegments/add.md, iis/configuration/system.webServer/security/requestFiltering/index.md, iis/configuration/system.webServer/webdav/authoring/index.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/sql-2008-for-hosters.md, iis/web-hosting/joining-the-web-hosting-gallery/create-welcome-e-mails.md, iis/web-hosting/planning-the-web-hosting-architecture/iis-extensibility.md
This PR fixes 83 missing alt text issues from iis-docs file.
=> [Bulk] Validation-Missing-Alttext3

iis/media/transform-manager/transforming-media-files-to-on-demand-smooth-streams.md
Added alternate texts to all the screenshots in the file.
=> [Bulk| Validations: Fix missing alt text issues 2

iis/publish/using-web-deploy/building-a-web-deploy-package-from-visual-studio-2010.md
=> Alt Text Addition

iis/manage/configuring-security/application-pool-identities-and-sql-server-express.md, iis/publish/deploying-application-packages/screwturn-wiki.md
This PR fixes alt text issues.
=> [Bulk| Validations: Fix missing alt text issues 3

iis/configuration/system.applicationHost/sites/site/ftpServer/customFeatures/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/commandFiltering/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/logFile/customFields/index.md, iis/configuration/system.ftpServer/caching/index.md, iis/configuration/system.webServer/applicationInitialization/add.md, iis/configuration/system.webServer/httpCompression/index.md, iis/configuration/system.webServer/httpCompression/scheme.md, iis/configuration/system.webServer/isapiFilters/filter.md, iis/configuration/system.webServer/security/authentication/windowsAuthentication/providers/add.md, iis/configuration/system.webServer/security/requestFiltering/requestLimits/headerLimits/index.md, iis/configuration/system.webServer/tracing/traceFailedRequests/add/traceAreas/index.md, iis/configuration/system.webServer/webdav/authoring/fileSystem.md
This PR fixes 80 Missing Alt text issues in iis-docs file.
=> [Bulk] Validation-Missing-Alttext-4

iis/develop/using-webmatrix/creating-a-content-feed-for-learning.md, iis/extensions/url-rewrite-module/creating-rewrite-rules-for-the-url-rewrite-module.md, iis/get-started/planning-for-security/build-a-custom-iis-server.md, iis/get-started/whats-new-in-iis-8/iis-80-multicore-scaling-on-numa-hardware.md, iis/get-started/whats-new-in-iis-8/iis-80-server-name-indication-sni-ssl-scalability.md, iis/install/installing-iis-7/install-and-configure-iis-on-server-core.md, iis/install/installing-publishing-technologies/installing-and-configuring-webdav-on-iis.md, iis/manage/provisioning-and-managing-iis/shared-configuration-and-remote-provisioning.md, iis/publish/using-web-deploy/introduction-to-web-deploy.md, iis/web-hosting/web-server-for-shared-hosting/administration-pack.md
This PR fixes 70 missing alt text issues.
=> [Bulk] Validation: Fix missing alt text issues 3/22

iis/configuration/system.applicationHost/sites/index.md, iis/configuration/system.webServer/security/dynamicIpSecurity/denyByRequestRate.md, iis/install/installing-iis-7/how-to-install-aspnet-11-with-iis-on-vista-and-windows-2008.md, iis/manage/configuring-security/ensure-security-isolation-for-web-sites.md, iis/manage/provisioning-and-managing-iis/hosted-services-control-panels.md, iis/media/on-demand-smooth-streaming/getting-started-with-iis-smooth-streaming.md, iis/publish/using-the-ftp-service/configuring-ftp-user-isolation-in-iis-7.md
=> Alt Text Inclusion

iis/configuration/system.applicationHost/sites/site/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/customFeatures/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/ssl.md, iis/configuration/system.webServer/asp/index.md, iis/configuration/system.webServer/security/ipSecurity/index.md, iis/configuration/system.webServer/security/requestFiltering/hiddenSegments/index.md, iis/configuration/system.webServer/staticContent/clientCache.md, iis/configuration/system.webServer/staticContent/mimeMap.md, iis/develop/runtime-extensibility/sample-image-watermark-module.md, iis/install/installing-publishing-technologies/installing-and-configuring-web-deploy.md, iis/media/web-playlists/web-playlists-for-iis-extending-output-formats-using-xslt.md
This PR fixes 60 missing alt text issues.
=> [Bulk] Validation: Fix Missing Alt Text 3/23-ck

iis/media/transform-manager/encrypting-on-demand-smooth-streams.md
Added alternate texts for screenshots.
=> [Bulk| Validations: Fix missing alt text issues 4

iis/configuration/system.ftpServer/security/requestFiltering/denyUrlSequences/index.md, iis/configuration/system.webServer/security/authentication/windowsAuthentication/extendedProtection/index.md, iis/configuration/system.webServer/webdav/globalSettings/lockStores/index.md, iis/extensions/url-rewrite-module/using-global-and-distributed-rewrite-rules.md, iis/publish/using-the-ftp-service/creating-a-new-ftp-site-in-iis-7.md
This PR fixes 37 missing alt text issues.
=> [Bulk] Validation: Fix alt text issues in iis-docs

iis/configuration/system.applicationHost/serviceAutoStartProviders/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/bindings/binding.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/messages.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/userIsolation/activeDirectory.md, iis/configuration/system.webServer/handlers/index.md, iis/configuration/system.webServer/management/authentication/credentials/add.md, iis/configuration/system.webServer/management/trustedProviders/add.md, iis/configuration/system.webServer/security/authentication/windowsAuthentication/extendedProtection/spn.md, iis/configuration/system.webServer/security/requestFiltering/denyQueryStringSequences/index.md, iis/configuration/system.webServer/security/requestFiltering/filteringRules/index.md, iis/configuration/system.webServer/security/requestFiltering/verbs/index.md, iis/configuration/system.webServer/webdav/authoring/properties/index.md, iis/troubleshoot/using-failed-request-tracing/troubleshooting-failed-requests-using-tracing-in-iis-85.md, iis/web-hosting/joining-the-web-hosting-gallery/configure-site-for-web-deploy-publishing.md, iis/web-hosting/microsoft-web-farm-framework-20-for-iis-7/system-and-platform-requirements-for-the-web-farm-framework-20-for-iis.md
This PR fixes 82 missing alt text issues in iis-docs file.
=> [Bulk] Validation-Missing-Alttext-5

iis/configuration/system.ftpServer/security/requestFiltering/hiddenSegments/index.md, iis/media/transform-manager/sending-transform-manager-job-status-notifications-to-a-remote-web-application.md, iis/media/transform-manager/transforming-media-files-to-apple-http-live-streams.md, iis/media/web-playlists/web-playlists-for-iis-serving-media-content-from-user-folders.md, iis/troubleshoot/performance-issues/troubleshooting-native-memory-leak-in-an-iis-7x-application-pool.md, iis/web-hosting/hosting-the-microsoft-web-platform-on-amazon-ec2/amazon-ec2-microsoft-web-platform-images-media-server.md
This PR fixes 87 missing alt text issues.
=> [Bulk] Validation: Fix Alttext issues (iis-docs) 3/24/22

iis/configuration/system.ftpServer/security/requestFiltering/denyUrlSequences/index.md, iis/configuration/system.webServer/security/authentication/windowsAuthentication/extendedProtection/index.md, iis/configuration/system.webServer/security/requestFiltering/denyUrlSequences/add.md, iis/configuration/system.webServer/webdav/globalSettings/lockStores/index.md, iis/extensions/url-rewrite-module/using-global-and-distributed-rewrite-rules.md, iis/get-started/planning-your-iis-architecture/the-configuration-system-in-iis-7.md, iis/publish/using-the-ftp-service/creating-a-new-ftp-site-in-iis-7.md, iis/web-hosting/configuring-servers-in-the-windows-web-platform/configure-your-servers-for-the-windows-web-hosting-platform.md
This PR fixes 31 missing alt text issues
=> [Bulk] Validation: Fix Alttext issues in iis-docs

iis/configuration/system.webServer/webdav/globalSettings/propertyStores/index.md
Added alternate texts to screenshots.
=> [Bulk| Validations: Fix missing alt text issues 5

iis/configuration/system.webServer/defaultDocument/files/add.md, iis/configuration/system.webServer/security/requestFiltering/requestLimits/headerLimits/add.md, iis/manage/managing-performance-settings/configure-iis-7-output-caching.md, iis/publish/using-webdav/how-to-use-custom-properties-with-webdav.md, iis/web-hosting/microsoft-web-farm-framework-20-for-iis-7/web-farm-framework-20-for-iis-code-sample.md, iis/web-hosting/web-server-for-shared-hosting/default-documents.md
This PR fixes 18 missing alt text issues.
=> [Bulk] Validation: Fix Missing Alttext (iis-docs)

iis/application-frameworks/running-php-applications-on-iis/build-a-high-performance-php-stack-with-windows-iis-and-zend-server.md, iis/configuration/system.applicationHost/applicationPools/add/recycling/index.md, iis/configuration/system.ftpServer/security/requestFiltering/fileExtensions/add.md, iis/configuration/system.ftpServer/security/requestFiltering/index.md, iis/configuration/system.webServer/management/authentication/providers/index.md, iis/configuration/system.webServer/security/authentication/iisClientCertificateMappingAuthentication/oneToOneMappings/index.md, iis/configuration/system.webServer/security/authentication/index.md, iis/get-started/planning-your-iis-architecture/understanding-multicore-scaling-on-numa-hardware-with-iis-8.md, iis/manage/provisioning-and-managing-iis/services-overview.md, iis/media/transform-manager/delivering-transform-manager-output-to-clients.md, iis/web-hosting/hosting-the-microsoft-web-platform-on-amazon-ec2/amazon-ec2-microsoft-web-platform-dotnetnuke.md
This PR fixes 61 missing alt text issues.
=> [Bulk] Validation: Fix missing alt text 3/24

iis/configuration/system.applicationHost/sites/site/virtualDirectoryDefaults.md
This PR fixes three missing alt text issues.
=> [Bulk]validation: missing alt textcc

iis/publish/using-web-deploy/web-deploy-parameterization.md
Adding alternate texts to screenshots.
=> [Bulk| Validations: Fix missing alt text issues 7

iis/configuration/system.applicationHost/applicationPools/add/index.md, iis/configuration/system.applicationHost/sites/applicationDefaults.md, iis/configuration/system.applicationHost/sites/site/application/index.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/customAuthentication/index.md, iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/customAuthentication/providers/index.md, iis/configuration/system.applicationHost/sites/site/ftpServer/userIsolation/index.md, iis/configuration/system.webServer/asp/comPlus.md, iis/configuration/system.webServer/httpProtocol/customHeaders/index.md, iis/configuration/system.webServer/security/requestFiltering/filteringRules/filteringRule/scanHeaders/index.md, iis/configuration/system.webServer/security/requestFiltering/verbs/add.md, iis/configuration/system.webServer/tracing/traceProviderDefinitions/index.md, iis/develop/using-visual-studio-with-iis/using-visual-studio-2008-with-iis.md, iis/manage/scripting/get-to-know-the-iis-wmi-provider-using-cim-studio.md
This PR fixes 89 issues from missing alt text file from iis-docs.
=> [Bulk]Validation-Missing-Alltext6

iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/index.md, iis/configuration/system.webServer/globalModules/add.md, iis/configuration/system.webServer/httpErrors/index.md, iis/configuration/system.webServer/management/authentication/providers/add.md, iis/configuration/system.webServer/security/requestFiltering/alwaysAllowedQueryStrings/add.md, iis/configuration/system.webServer/webdav/globalSettings/propertyStores/add.md
=> [Bulk]validation: fix missing alt text 4/01

iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/customAuthentication/providers/index.md, iis/configuration/system.webServer/fastCgi/application/environmentVariables/index.md
- Added alternate texts to all the screenshots.
- Convert absolute link to relative link.
=> [Bulk| Validations: Fix missing alt text issues 9

iis/overview/centralized-web-farm-management.md
=> [BrokenLinksH2] Fixed the link path

iis/get-started/planning-your-iis-architecture/deep-dive-into-iis-configuration-with-iis-7-and-iis-8.md
[Internal Review](https://review.docs.microsoft.com/en-us/IIS/get-started/planning-your-iis-architecture/deep-dive-into-iis-configuration-with-iis-7-and-iis-8?branch=pr-en-us-514)
Added the missing section names.
=> Fixed #478.

iis/configuration/system.ftpServer/providerDefinitions/activation/index.md
Add missing alt text to six images.
This PR fixes changes in one file.
=> [bulk] Validation: missing alt text

iis/configuration/system.ftpServer/security/authorization/add.md, iis/ftp-extensibility-reference/native-code-api-reference/iftplogprovider-interface-native.md
Added missing image alt text and adjusted column headers to display correctly.
=> Validation: Added Missing Alt Text and Adjusted Column Headers

iis/extensions/smooth-streaming-client/manifeststream-parentstream-property.md, iis/extensions/smooth-streaming-client/smoothstreamingerroreventargs-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/ilogger-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdefinition-addconfigurationmessage-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdefinition-fields-microsoft-web-media-transformmanager.md, iis/extensions/troubleshooting-application-request-routing/troubleshooting-cache-items-arr-v2.md, iis/extensions/web-playlists/playlist-property-type-enumeration.md
=> Validation: Added Missing Column Headers

iis/configuration/system.webServer/tracing/traceFailedRequests/add/index.md, iis/extensions/configuring-application-request-routing-arr/configure-caching-with-query-string-support-in-application-request-routing.md, iis/extensions/smooth-streaming-client/cacherequest2-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/cacherequest2-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-setdownloadbuffersec-method.md
Added alt-text and missing column headers and corrected descriptions in metadata.
=> Validation: Added alt-text and column headers

iis/application-frameworks/install-and-configure-php-on-iis/how-to-secure-the-microsoft-web-platform.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-content-in-iis-through-impersonation.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-your-infrastructure-and-php-applications.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-a-simple-ftp-authentication-provider.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-a-simple-ftp-home-directory-provider.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-a-simple-ftp-logging-provider.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-authentication-provider-using-an-xml-database.md, iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-provider-that-sends-an-email-when-files-are-uploaded.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-home-directory-provider.md, iis/develop/installingpublishing-apps-with-webmatrix/atomsite-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/dotnetnuke-community-edition-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/joomla-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/kentico-cms-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/mayando-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/nservice-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/phpbb-faq.md, iis/develop/installingpublishing-apps-with-webmatrix/wordpress-faq.md, iis/extensions/database-manager/working-with-stored-procedures.md, iis/extensions/database-manager/working-with-views.md, iis/get-started/planning-for-security/secure-content-in-iis-through-file-system-acls.md, iis/get-started/whats-new-in-iis-7/what39s-new-for-microsoft-and-ftp-in-iis-7.md, iis/install/installing-publishing-technologies/installing-and-configuring-ftp-7-on-iis-7.md, iis/publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7.md, iis/publish/using-the-ftp-service/using-ftp-over-ssl-in-iis-7.md, iis/publish/using-the-ftp-service/using-ftp-virtual-host-names-in-iis-7.md
=> Validation: Duplicate-descriptions fixes.

iis/extensions/database-manager-reference/column-name-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/databaseprovider-executequery-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/foreignkey-ismarkedfordelete-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/foreignkey-name-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbrestoremanager-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/view-class-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/adaptivesourcefailedeventargs-failtype-property.md, iis/extensions/smooth-streaming-client/adaptivesourcemanager-setplaybackoffsetsec-method.md, iis/extensions/smooth-streaming-client/clipcontext-playbackduration-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/clipcontext-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/clipinformation-issmoothstreamingsource-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipplaybackeventargs-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/iadaptivesource-manifestreadyevent-event.md, iis/extensions/smooth-streaming-client/idownloaderplugin-interface.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-nominalbitrate-property.md, iis/extensions/smooth-streaming-client/manifesttrack-fourcc-property.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-downloadprogress-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-endposition-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-scheduleclip-method-clipinformation-boolean-timespan-object-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/iisnamespaces-taskdefinitionnamespace-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-methods-microsoft-web-media-transformmanager.md, iis/wmi-provider/applicationcontainsconfigurationsection-class.md, iis/wmi-provider/configuredobject-getsection-method.md, iis/wmi-provider/deviceelement-class.md, iis/wmi-provider/expressionbuildersettings-class.md, iis/wmi-provider/isapifilterelement-class.md, iis/wmi-provider/manytoonecertificatemappingelement-class.md, iis/wmi-provider/segmentelement-class.md, iis/wmi-provider/traceproviderdefinition-class.md, iis/wmi-provider/virtualdirectorycontainsconfigurationsection-class.md
=> Validation: Added Missing Descriptions

iis/extensions/smooth-streaming-client/circularlist-t-lastindexof-method-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/clipinformation-constructor-boolean-uri-uri-duration-ismoothstreamingcache-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/protectioninfo-protectionheader-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-constructor-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-parseexternalmanifest-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/test-and-debug-applications-iis-smooth-streaming.md, iis/extensions/smooth-streaming-client/tracing-includetime-field-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-management-rest-services/incomingbitrate-element.md, iis/extensions/transform-manager/configurationmessage-constructor-xelement-configurationbase-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/configurationmessage-helplinkid-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-jobmanagerloglevel-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsprogress-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsqueuetime-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-outputfolderpath-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-createpropertyelement-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-dispose-method-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/application-host-administration-api-reference.md, iis/web-development-reference/native-code-api-reference/chttpmodule-class.md, iis/web-development-reference/native-code-api-reference/chttpmodule-oncustomrequestnotification-method.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onsendresponse-method.md, iis/web-development-reference/native-code-api-reference/iappdomaininfoenum-interface.md, iis/web-development-reference/native-code-api-reference/iapphostmethodcollection-item-property.md, iis/web-development-reference/native-code-api-reference/iglobaltraceeventprovider-interface.md, iis/web-development-reference/native-code-api-reference/ihttpfilemonitor-getmodulecontextcontainer-method.md, iis/web-development-reference/native-code-api-reference/ihttpmodulefactory-terminate-method.md, iis/web-development-reference/native-code-api-reference/ihttpresponse-writeentitychunks-method.md, iis/web-development-reference/native-code-api-reference/ilistenerchannelcallback-reportstarted-method.md, iis/web-development-reference/native-code-api-reference/iurikey-updatefrequentlyhittickcount-method.md, iis/web-development-reference/native-code-api-reference/web-server-core-structures.md
=> [Bulk] Validation: validation fixes JM 5/18

iis/extensions/smooth-streaming-client/cacheresponse2-constructor-int64-string-webheadercollection-stream-httpstatuscode-string-datetime-boolean-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/moveprev-method.md, iis/extensions/smooth-streaming-client/position-in-stream.md, iis/extensions/smooth-streaming-client/seekcompletedeventargs-actualseekposition-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-configpath-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-constructor-list-streamupdatedeventargs-object-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/trackinfo-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/configurationmessage-regkeyfound-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/iisnamespaces-mediaservices-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/iisnamespaces-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-resubmitjob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanifestproperty-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-schedulermemory-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-watchfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-manifestextension-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-settaskindex-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-deletejobtemplate-method-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistentryinfocollection-count-property.md, iis/extensions/web-playlists/iplaylistfileinfo-getstream-method.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onlogrequest-method.md, iis/web-development-reference/native-code-api-reference/iapphostpropertyextension-interface.md, iis/web-development-reference/native-code-api-reference/iapphostsectiongroup-deletesectiongroup-method.md, iis/web-development-reference/native-code-api-reference/icustomaction2resultcallback-interface.md, iis/web-development-reference/native-code-api-reference/ihttpcachekey-enum-method.md, iis/web-development-reference/native-code-api-reference/ihttpfileinfo-accesscheck-method.md, iis/web-development-reference/native-code-api-reference/ihttpurlinfo-getmodulecontextcontainer-method.md, iis/web-development-reference/native-code-api-reference/iurikey-getcachename-method.md, iis/web-development-reference/native-code-api-reference/native-configuration-api-reference.md, iis/web-development-reference/native-code-api-reference/web-server-core-classes.md, iis/web-development-reference/native-code-api-reference/web-server-core-constants.md
=> Validation: description-missing fixes.

iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-authentication-provider-with-dynamic-ip-restrictions.md, iis/develop/developing-for-ftp/how-to-use-managed-code-visual-basic-to-create-a-simple-ftp-home-directory-provider.md, iis/develop/developing-for-ftp/how-to-use-managed-code-visual-basic-to-create-a-simple-ftp-logging-provider.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-authentication-provider.md, iis/develop/developing-for-ftp/how-to-use-native-code-c-to-create-a-simple-ftp-logging-provider.md, iis/extensions/smooth-streaming-client/cacheresponse2-usedtrack-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/chunkresult-timestamp-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipinformation-constructor-boolean-uri-uri-duration-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-mediafailed-event-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-source-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/tracing-includedate-field-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/tracing-trace-method-string-string-string-tracearea-tracelevel-string-object[]-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-management-rest-services/delete-a-publishing-point.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-server-manifest-live-smil-element.md, iis/extensions/transform-manager/jobdefinition-logretentionperioddisplayunit-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestpropertiesdictionary-constructor-microsoft-web-media-transformmanager_1.md, iis/extensions/transform-manager/scheduler-initialize-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/schedulerinfo-concurrentjobs-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-deletejob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-getassemblyinfo-method-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistfileinfo-interface.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onpostbeginrequest-method.md, iis/web-development-reference/native-code-api-reference/iappdomaininfo-getisidle-method.md, iis/web-development-reference/native-code-api-reference/iapphostmethodextension-providemethod-method.md, iis/web-development-reference/native-code-api-reference/ihttpperfcounterinfo-decrementcounter-method.md, iis/web-development-reference/native-code-api-reference/ihttprequest2-interface.md, iis/web-development-reference/native-code-api-reference/ihttprequest3-interface.md, iis/web-development-reference/native-code-api-reference/ihttptracecontext-gettraceconfiguration-method.md, iis/web-development-reference/native-code-api-reference/web-server-core-interfaces.md, iis/web-development-reference/native-code-api-reference/worker-process-and-protocol-manager-interfaces.md
description-missing and duplicate-descriptions fixes.
=> Validation: description-missing and duplicate-descriptions fixes.

iis/extensions/database-manager-reference/databaseprovider-constructor-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-name-property-microsoft-web-management-databasemanager.md, iis/extensions/express-api-reference/cleariisenvironmentvariables.md, iis/extensions/smooth-streaming-client/adaptivesourcestatusupdatedeventargs-endtime-property.md, iis/extensions/smooth-streaming-client/adaptivesourcestatusupdatedeventargs-starttime-property.md, iis/extensions/smooth-streaming-client/cacheresponse-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/downloaderrequest-class.md, iis/extensions/smooth-streaming-client/downloaderresponse-uri-property.md, iis/extensions/smooth-streaming-client/fast-forward-and-rewind-modes-iis-smooth-streaming.md, iis/extensions/smooth-streaming-client/manifest-dvrwindowlength-property.md, iis/extensions/smooth-streaming-client/protectionheader-protectiondata-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/seekcompletedeventargs-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/segmentinfo-selectedstreams-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothschemehandler-setproperties-method.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-fields-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-onapplytemplate-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-fields-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/trackinfo-customattributes-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/errormessage-element.md, iis/extensions/smooth-streaming-management-rest-services/segmentlength-element.md, iis/extensions/transform-manager/ijobmetadata-inputfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imonitoringservice-getrunningjobs-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-createworkitemelement-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-shutdowncomplete-event-microsoft-web-media-transformmanager.md, iis/wmi-provider/applicationdependenciessection-class.md, iis/wmi-provider/assemblyelement-class.md, iis/wmi-provider/directorysettings-class.md, iis/wmi-provider/objectconfigurationassociation-class.md, iis/wmi-provider/systemcodedomsection-class.md, iis/wmi-provider/traceurlareasettings-class.md
=> [Bulk] Validation: validation fixes JM 5/18a

iis/extensions/database-manager-reference/columndatainfo-class-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbviewmanager-createview-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/tableinfo-class-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-methods-microsoft-web-management-databasemanager.md, iis/extensions/express-api-reference/getpropertyvalue.md, iis/extensions/search-engine-optimization-toolkit/iis-search-engine-optimization-toolkit.md, iis/extensions/smooth-streaming-client/adaptivesource-manifest-property.md, iis/extensions/smooth-streaming-client/adaptivesourcefailedeventhandler-delegate.md, iis/extensions/smooth-streaming-client/adaptivesourceopenedeventargs-class.md, iis/extensions/smooth-streaming-client/chunkinfo-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipeventargs-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-beginpersist-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-endretrieve-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifest-islive-property.md, iis/extensions/smooth-streaming-client/microsoft-web-media-smoothstreaming-namespace.md, iis/extensions/smooth-streaming-client/segmentinfo-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-bufferingprogress-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-liveplaybackstartposition-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-seekcompleted-event-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-timestamp-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-trace-method-tracearea-tracelevel-string-object[]-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/trackinfo-bitrate-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/transform-manager/itaskstatus-status-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-concurrentjobs-property-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iis-web-playlists-sdk-programming-reference.md, iis/wmi-provider/clienttargetsection-class.md, iis/wmi-provider/configurationsection-class.md, iis/wmi-provider/customheadersettings-class.md, iis/wmi-provider/smtpmailsettingssection-class.md
=> [Bulk] Validation: validation fixes JM 5/19

iis/extensions/database-manager-reference/databaseprovider-getdatabasehostname-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/databaseprovider-testconnection-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/foreignkey-fktablename-property-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/cacheresponse-readfrom-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/cacheresponse-statuscode-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/circularlist-t-reverse-method-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/clipeventargs-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipinformation-clipuri-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-stream-property.md, iis/extensions/smooth-streaming-client/manifeststream-getattribute-method.md, iis/extensions/smooth-streaming-client/manifesttrack-maxheight-property.md, iis/extensions/smooth-streaming-client/manifesttrack-nalunitlength-property.md, iis/extensions/smooth-streaming-client/select-and-monitor-bitrate.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-autoplay-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-latencycorrectionthreshold-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-streamupdatedaction-enumeration-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-enabletracearea-method-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/trackchangedeventargs-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/incomingfragmentduration-element.md, iis/extensions/transform-manager/hpcscheduler-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/hpcscheduler-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-nodetaskcodepathx64-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-instanceid-property-microsoft-web-media-transformmanager.md, iis/wmi-provider/hostingenvironmentsection-class.md, iis/wmi-provider/listeneradapterssection-class.md, iis/wmi-provider/membershipsection-class.md, iis/wmi-provider/onetoonecertificatemappingelement-class.md, iis/wmi-provider/sqlcachedependencysection-class.md, iis/wmi-provider/urlcompressionsection-class.md, iis/wmi-provider/webservicesprotocolelement-class.md
=> [Bulk] Validation: validation fixes 5/19a

iis/extensions/database-manager-reference/columndatainfo-properties-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedureparameters-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbtablemanager-gettableinfo-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbviewmanager-interface-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/indexcolumn-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/table-createdate-property-microsoft-web-management-databasemanager.md, iis/extensions/express-api-reference/express-api-reference.md, iis/extensions/express-api-reference/iiisexpressprocessutility.md, iis/extensions/express-api-reference/microsoft-web-diagnostics-iis-express.md, iis/extensions/smooth-streaming-client/adaptivesourcemanager-adaptivesourceopenedevent-event.md, iis/extensions/smooth-streaming-client/adaptivesourcemanager-adaptivesources-property.md, iis/extensions/smooth-streaming-client/cacheresponse-expirytime-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/imanifeststream-getiterator-method.md, iis/extensions/smooth-streaming-client/microsoft-media-adaptivestreaming-namespace.md, iis/extensions/smooth-streaming-client/setplaybackrangecompletedeventargs-rightedge-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentstatechanged-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/ssmelogreadyroutedeventhandler-delegate-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-attributes-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-shutdown-method-microsoft-web-media-diagnostics_1.md, iis/extensions/transform-manager/configurationbase-lastmodified-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsroot-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanager-schedulerinfo-property-microsoft-web-media-transformmanager.md, iis/wmi-provider/aspcomplus-class.md, iis/wmi-provider/headerlimitselement-class.md, iis/wmi-provider/httploggingsection-class.md, iis/wmi-provider/redirectheadersettings-class.md, iis/wmi-provider/site-class.md, iis/wmi-provider/soapextensiontypeelement-class.md, iis/wmi-provider/tagprefixelement-class.md, iis/wmi-provider/tracesection-class.md
=> [Bulk] Validation: validation fixes JM 5/19b

iis/extensions/database-manager-reference/table-constructor-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/adaptivesourcefailedeventargs-httpresponse-property.md, iis/extensions/smooth-streaming-client/cacherequest-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/cacheresponse-writeto-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/chunkinfo-structure.md, iis/extensions/smooth-streaming-client/chunkrequesttype-enumeration-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/chunkresult-chunkdata-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/circularlist-t-copyto-method-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/clipinformation-constructor-boolean-uri-duration-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifest-getattribute-method.md, iis/extensions/smooth-streaming-client/manifestinfo-events-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-stop-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-tracefunctionentry-method-string-string-tracearea-microsoft-web-media-diagnostics.md, iis/extensions/transform-manager/imanagementservice-updatecredential-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/itaskstatus-updatestatus-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-jobmanagerlogrolloverintervaldisplayunit-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-cultureinfomoniker-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdefinition-constructor-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistentryinfocollection-interface.md, iis/extensions/web-playlists/iplaylistfileinfo-lastmodifiedtime-property.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onpostupdaterequestcache-method.md, iis/web-development-reference/native-code-api-reference/iapphostconfiglocation-interface.md, iis/web-development-reference/native-code-api-reference/iapphostconfiglocation-item-property.md, iis/web-development-reference/native-code-api-reference/iapphostmappingextension-mappath-method.md, iis/web-development-reference/native-code-api-reference/iapphostproperty-interface.md, iis/web-development-reference/native-code-api-reference/icacheprovider-interface.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-getparentcontext-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver-dispensecontainer-method.md, iis/web-development-reference/native-code-api-reference/isendresponseprovider-getheadersbeingsent-method.md
=> [Bulk] Validation: validation fixes JM 5/23b

iis/extensions/smooth-streaming-client/chunkresult-error-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/clipprogress-enumeration-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingexception-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-downloadprogresschanged-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-sourceproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-selectedtracks-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/traceentry-properties-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/tracing-trace-method-string-string-tracearea-tracelevel-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackchangedeventargs-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/track-element.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-server-manifest-on-demand-video-param-element.md, iis/extensions/transform-manager/hpcscheduler-getjobcompletiondetails-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/iisnamespaces-rdf-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-startjobmanager-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-updatetaskdefinition-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmetadata-constructor-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/logger-writeline-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-class-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/cglobalmodule-onglobalhealthcheck-method.md, iis/web-development-reference/native-code-api-reference/iapphostconfigfile-locations-property.md, iis/web-development-reference/native-code-api-reference/iapphostelement-interface.md, iis/web-development-reference/native-code-api-reference/iapphostpropertyschema-name-property.md, iis/web-development-reference/native-code-api-reference/ihttpapplication-getappconfigpath-method.md, iis/web-development-reference/native-code-api-reference/ihttpresponse-closeconnection-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver2-gettoken-method.md, iis/web-development-reference/native-code-api-reference/ihttpuser-referenceuser-method.md, iis/web-development-reference/native-code-api-reference/iwebsocketcontext-canceloutstandingio-method.md, iis/web-development-reference/native-code-api-reference/windows-process-activation-service-functions.md, iis/web-development-reference/native-code-api-reference/wpf-interface-id-enum-enumeration.md
=> [Bulk] Validation: Fixed missing descriptions (5/23)

iis/extensions/smooth-streaming-client/chunkresult-chunkresultstate-enumeration-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipinformation-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipplaybackeventargs-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingerroreventargs-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingerroreventargs-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-attributesproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-audiostreamindex-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-bufferingprogress-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-islive-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-scheduleclip-method-clipinformation-boolean-object-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-seekcompleted-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-setplaybackrangecompletedeventhandler-delegate-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-restricttracks-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-tracefunctionexit-method-string-string-string-tracearea-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-tracefunctionexit-method-tracearea-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/trackinfo-begingetchunk-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-management-rest-services/lastoutputfragmenttimestamp-element.md, iis/extensions/transform-manager/configurationbase-configurationdirectory-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-concurrentjobs-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-constructor-fileinfo-xelement-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-outputfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-starttime-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-getcredential-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-initialize-method-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistentryinfo-getproperty-method.md, iis/extensions/web-playlists/writing-a-managed-web-playlist-provider.md, iis/web-development-reference/native-code-api-reference/ihttptracecontext-gettraceactivityid-method.md, iis/web-development-reference/native-code-api-reference/pfn-webhost-listener-application-pool-created-function.md, iis/wmi-provider/fastcgisection-class.md
=> [Bulk] Validation: validation fixes JM 5/23a

iis/extensions/database-manager-reference/column-scale-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/databaseinfo-constructor-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/microsoft-web-management-databasemanager-namespace.md, iis/extensions/database-manager-reference/querycolumnmetadata-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/storedprocedureparameter-tag-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/table-properties-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/chunkinfo-timestamp-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/circularlist-t-findindex-method-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/clipinformation-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-fourcc-property.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-endpersist-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifeststream-displaywidth-property.md, iis/extensions/smooth-streaming-client/smoothstreamingasyncresult-constructor-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingexception-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamchangedaction-enumeration.md, iis/extensions/smooth-streaming-client/streaminfo-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-constructor-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/test-and-debug-an-implementation-of-ismoothstreamingcache.md, iis/extensions/smooth-streaming-client/tracing-trace-method-string-string-tracearea-tracelevel-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-tracefunctionexit-method-tracearea-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackinfo-compareto-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/autorestartonencoderreconnect-element.md, iis/extensions/smooth-streaming-management-rest-services/service-management-status-and-error-codes.md, iis/extensions/transform-manager/jobdefinition-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-canceljob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/schedulerprovider-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-taskindex-property-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/iappdomaininfo-getid-method.md, iis/web-development-reference/native-code-api-reference/iapphostelement-properties-property.md
=> [Bulk] Validation: validation fixes JM 5/23

iis/extensions/database-manager-reference/indexcolumn-constructor-microsoft-web-management-databasemanager.md, iis/extensions/express-api-reference/applyiisenvironmentvariables.md, iis/extensions/smooth-streaming-client/advancedloggingplugin-manifestlogurls-property-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/cacherequest-constructor-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/circularlist-t-lastindexof-method-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/clipinformation-setsource-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/iadaptivesource-interface.md, iis/extensions/smooth-streaming-client/ihttpcookie-name-property.md, iis/extensions/smooth-streaming-client/ismoothstreamingcache-beginretrieve-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifest-lookaheadcount-property.md, iis/extensions/smooth-streaming-client/manifestinfo-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/manifeststream-availabletracks-property.md, iis/extensions/smooth-streaming-client/microsoft-web-media-namespace-reference.md, iis/extensions/smooth-streaming-client/movenext-method.md, iis/extensions/smooth-streaming-client/qualitylevel-attributes.md, iis/extensions/smooth-streaming-client/seekcompletedeventargs-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-bufferingtimeproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-clippositionproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-liveplaybackoffsetproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamchangedresult-stream-property.md, iis/extensions/smooth-streaming-management-rest-services/query-publishing-point-statistics.md, iis/extensions/transform-manager/ilogger-logfile-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/itaskstatus-interface-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-save-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-taskindex-property-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/iapphostconstantvalue-value-property.md, iis/web-development-reference/native-code-api-reference/iapphostproperty-setmetadata-method.md, iis/web-development-reference/native-code-api-reference/iglobalfilechangeprovider-getfilename-method.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-getscripttranslated-method.md, iis/wmi-provider/httpwebrequestsettings-class.md
=> [Bulk] Validation: validation fixes JM 5/20c

iis/extensions/database-manager-reference/tableinfo-columns-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-isvariablelength-property-microsoft-web-management-databasemanager.md, iis/extensions/express-api-reference/clearmanifestcontext.md, iis/extensions/express-api-reference/iiisuserdata.md, iis/extensions/smooth-streaming-client/adaptivesourcemanager-sendextendedcommand-method.md, iis/extensions/smooth-streaming-client/advancedloggingplugin-smoothstreamingmediaelement-property-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/circularlist-t-methods-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/clipplaybackeventargs-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-interface.md, iis/extensions/smooth-streaming-client/imanifesttrack-interface-maxwidth-property.md, iis/extensions/smooth-streaming-client/manifestinfo-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/microsoft-web-media-namespace-reference_1.md, iis/extensions/smooth-streaming-client/smoothstreamingasyncresult-completedsynchronously-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-flushbuffers-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-mediaended-event-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalduration-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-smoothstreamingcacheproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-startseektolive-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-class-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-includethreadid-field-microsoft-web-media-diagnostics_1.md, iis/extensions/transform-manager/hpcscheduler-initialize-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsstatus-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-addconfigurationmessage-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-dispose-method-boolean-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/loglevelhelper-getloglevel-method-string-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistentryinfo-uri-property.md, iis/wmi-provider/accesssection-class.md, iis/wmi-provider/aspcache-class.md, iis/wmi-provider/soaptransportimportertypeelement-class.md
=> Validation: descriptions

iis/extensions/smooth-streaming-client/iadaptivesourcemanagerstatics-interface.md, iis/extensions/smooth-streaming-client/playbackstartposition-enumeration-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-canseek-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-downloadtrackchanged-event-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-liveeventcompleted-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-parseexternalmanifest-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-management-rest-services/autostart-element.md, iis/extensions/smooth-streaming-management-rest-services/ouputstream-element.md, iis/extensions/smooth-streaming-management-rest-services/smoothstreaming-element.md, iis/extensions/transform-manager/configurationbase-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/eventviewer-eventsource-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/ijobmanifest-getschedulerinfo-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-getjobdefinition-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-priority-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-constructor-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-localschedulerfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestpropertiesdictionary-propertieselementname-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-constructor-xname-string-boolean-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-required-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-constructor-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-canceljob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-updatecredential-method-microsoft-web-media-transformmanager.md, iis/extensions/web-playlists/iplaylistrequestinfo-setservervariable-method.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onpostresolverequestcache-method.md, iis/web-development-reference/native-code-api-reference/destroycompression-function.md, iis/web-development-reference/native-code-api-reference/iapphostelementcollection-interface.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-getuser-method.md, iis/web-development-reference/native-code-api-reference/ihttpmoduleregistrationinfo-setpriorityforglobalnotification-method.md, iis/web-development-reference/native-code-api-reference/pfn-web-core-shutdown-function.md, iis/wmi-provider/urlmapping-class.md
=> [Bulk] Validation: validation fixes JM 5/23c

iis/extensions/database-manager-reference/column-changes-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/connectionargument-name-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/dependenciesmissingexception-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbcustombackuprestoremanager-listbackups-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-constructor-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-defaultprecision-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-tostring-method-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/clipinformation-clickthroughuri-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/httpcookie-expiretime-property.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-manifestreadyevent-event.md, iis/extensions/smooth-streaming-client/smoothstreamingerroreventargs-errorcode-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-audiostreamcount-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-configpathproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-ismuted-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-ismutedproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-disabletracedestination-method-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-enabletracelevel-method-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-includemediaelementid-field-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackchangedeventargs-timestamp-property-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/iisnamespaces-smil-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/itask-initialize-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/itaskstatus-percentcomplete-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-jobtemplateidattributename-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsjobdefinitionid-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdetails-childprocessid-property-microsoft-web-media-transformmanager.md, iis/wmi-provider/compilersettings-class.md, iis/wmi-provider/configurationsectionwithcollection-get-method.md, iis/wmi-provider/providerfactoryelement-class.md, iis/wmi-provider/sessionstatesection-class.md, iis/wmi-provider/verbelement-class.md
=> [Bulk] Validation Fixes AM

iis/extensions/smooth-streaming-client/chunkresult-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipplaybackeventargs-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-clipprogressupdate-event-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-enablegpuacceleration-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-setplaybackrangeasync-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-type-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/authentication-and-authorization.md, iis/extensions/transform-manager/configurationbase-fields-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/eventviewer-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/eventviewer-eventidinformation-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-cloneelement-method-microsoft-web-media-transformmanager.md, iis/extensions/web-platform-installer/microsoft-web-platform-installer.md, iis/extensions/web-playlists/iplaylistrequestinfo-format-property.md, iis/web-development-reference/native-code-api-reference/iappdomaininfo-getvirtualpath-method.md, iis/web-development-reference/native-code-api-reference/iapphostpathmapper2-interface.md, iis/web-development-reference/native-code-api-reference/iapphostproperty-value-property.md, iis/web-development-reference/native-code-api-reference/iapphostpropertyschema-isexpanded-property.md, iis/web-development-reference/native-code-api-reference/iapphostsectiondefinition-name-property.md, iis/web-development-reference/native-code-api-reference/iapphostsectiondefinitioncollection-addsection-method.md, iis/web-development-reference/native-code-api-reference/iglobalrscaqueryprovider-getoutputbuffer-method.md, iis/web-development-reference/native-code-api-reference/ihttpcachespecificdata-referencecachedata-method.md, iis/web-development-reference/native-code-api-reference/ihttpcompletioninfo-interface.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-getservervarchanges-method.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-postcompletion-method.md, iis/web-development-reference/native-code-api-reference/ihttpfileinfo-getmodulecontextcontainer-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver2-getapppoolconfigfile-method.md, iis/web-development-reference/native-code-api-reference/iscriptmapinfo-getpath-method.md, iis/web-development-reference/native-code-api-reference/iurikey-geturl-method.md, iis/web-development-reference/native-code-api-reference/iwebsocketcontext-closetcpconnection-method.md, iis/web-development-reference/native-code-api-reference/iworkerprocessframework-getcustominterface-method.md
=> [Bulk] Validation: Fixed missing descriptions 5/24

iis/extensions/database-manager-reference/idbbackupmanager-interface-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/storedprocedure-definition-property-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/clipinformation-usesmoothstreamingcache-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifesttrack-stream-property.md, iis/extensions/smooth-streaming-client/segmentinfo-selectedstreams-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-canpause-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streaminfo-uniqueid-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/tracing-includemediaelementid-field-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-client/tracing-remoteserveruri-property-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-management-rest-services/outputstreams-element.md, iis/extensions/smooth-streaming-management-rest-services/requestrate-element.md, iis/extensions/transform-manager/configurationmessage-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/hpcscheduler-getjobstatus-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-updatejobdefinition-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-inputfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-schedulernodegroups-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailstaskcount-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-settaskcount-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-constructor-xname-string-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/schedulerinfo-constructor-jobscheduler-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-settaskcount-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-initializeservice-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-isserviceinitialized-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/workqueue-failedjobs-property-microsoft-web-media-transformmanager.md, iis/ftp-extensibility-reference/native-code-api-reference/iftpproviderconstruct-construct-method.md, iis/web-development-reference/native-code-api-reference/iapphostelement-name-property.md, iis/web-development-reference/native-code-api-reference/windows-process-activation-service-interfaces.md, iis/web-development-reference/native-code-development-overview/designing-native-code-http-modules.md
=> [Bulk] Validation: validation fixes JM 5/24

iis/extensions/smooth-streaming-client/adaptivesourcemanager-adaptivesourcemanagerfailedevent-event.md, iis/extensions/smooth-streaming-client/cacheresponse-methods-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/chunkinfo-attributes-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/chunkinfo-duration-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-attributes-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/update-publishing-point-state.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-client-manifest.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-server-manifest-on-demand-audio-element.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-server-manifest-on-demand.md, iis/extensions/transform-manager/credential-class-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/credential-username-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/scheduler-submitjob-method-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-development-overview/creating-hosted-web-core-applications.md, iis/web-development-reference/native-code-development-overview/walkthrough-creating-a-global-level-http-module-by-using-native-code.md
This PR is to fix issues related to build validation messages.
=> Validation issues | 27 (BULK)

iis/extensions/database-manager-reference/index-ismarkedfordelete-property-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/clipcontext-properties-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/clipinformation-setsource-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/ihttpcookie-value-property.md, iis/extensions/smooth-streaming-client/imanifeststream-selectedtracks-property.md, iis/extensions/smooth-streaming-client/manifesttrack-audiotag-property.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-clipstatechanged-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-scheduleclip-method-clipinformation-clipcontext-object-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-schedulelinearclip-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-smoothstreamingplaybackmode-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-totalbytesdownloaded-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-videoplaybacktrackproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/ssmedrmsetupdecryptorcompletedeventargs-chunkinfo-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/ssmedrmsetupdecryptorcompletedeventargs-class-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/hpcscheduler-startjob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/ilogger-writeline-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/imanagementservice-getjobtemplates-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-taskidattributename-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/logger-logfilename-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-name-property-microsoft-web-media-transformmanager.md, iis/wmi-provider/configurationsectionwithcollection-add-method.md, iis/wmi-provider/configuredobject-class.md, iis/wmi-provider/groupdependency-class.md, iis/wmi-provider/httptracingsection-class.md, iis/wmi-provider/webproxyscriptsettings-class.md, iis/wmi-provider/wsdlhelpgeneratorinfo-class.md
=> Validation: Descriptions 

iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-stop-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/traceentry-tracelevel-property-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackinfo-customattributes-property-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/configurationmessage-severity-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailstaskindex-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-arguments-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-localschedulerid-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-constructor-xname-xelement-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-submitjob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/utilities-findelement-method-xcontainer-xnamespace-string-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/cglobalmodule-onglobalapplicationstart-method.md, iis/web-development-reference/native-code-api-reference/iapphostconfigexception-errorstring-property.md, iis/web-development-reference/native-code-api-reference/iapphostpropertyschema-iscasesensitive-property.md, iis/web-development-reference/native-code-api-reference/iapphostsectiondefinitioncollection-interface.md, iis/web-development-reference/native-code-api-reference/iapphostsectiongroup-item-property.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-clonecontext-method.md, iis/web-development-reference/native-code-api-reference/ihttpcontext3-getnamedcontextcontainer-method.md, iis/web-development-reference/native-code-api-reference/ihttprequest-getsiteid-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver-registerfilechangemonitor-method.md, iis/web-development-reference/native-code-api-reference/ihttpuser-getimpersonationtoken-method.md, iis/web-development-reference/native-code-api-reference/ilistenerchannelcallback-getid-method.md, iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-getrawelementcount-method.md, iis/web-development-reference/native-code-api-reference/iprocesshostfactoryhelper-interface.md, iis/web-development-reference/native-code-api-reference/iprocesspingcallback-interface.md, iis/web-development-reference/native-code-api-reference/iwebsocketcontext-interface.md, iis/web-development-reference/native-code-api-reference/iwebsocketcontext-readfragment-method.md, iis/web-development-reference/native-code-api-reference/iwpfapplicationinfoutil-interface.md, iis/web-development-reference/native-code-api-reference/request-processing-constants.md
This PR fixes 28 missing descriptions.
=> [Bulk] Validation: fix missing descriptions II 5/24 

iis/extensions/express-api-reference/iisdirectory.md, iis/extensions/smooth-streaming-client/advancedloggingplugin-methods-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/chunkresult-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/manifestinfo-selectstreamscompleted-event-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/seekcompletedeventargs-actualseekposition-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothschemehandler-class.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentsegmentindexproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-startseektolive-method-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/traceentry-tracearea-property-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/tracing-readtraceconfig-method-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/tracing-trace-method-string-string-tracearea-tracelevel-string-object[]-microsoft-web-media-diagnostics_1.md, iis/extensions/transform-manager/hpcscheduler-dispose-method-microsoft-web-media-transformmanager_1.md, iis/extensions/transform-manager/jobmanager-events-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-getmanifestelement-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobtemplate-save-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/logger-loglevel-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/schedulerinfo-methods-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/schedulerinfo-schedulertype-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-properties-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-getjobdefinition-method-microsoft-web-media-transformmanager.md, iis/ftp-extensibility-reference/native-code-api-reference/logging-parameters-structure.md, iis/web-development-reference/native-code-api-reference/iapphostcollectionschema-getaddelementschema-method.md, iis/web-development-reference/native-code-api-reference/iapphostconstantvalue-interface.md, iis/web-development-reference/native-code-api-reference/iapphostelement-collection-property.md, iis/web-development-reference/native-code-api-reference/iapphostpathmapper2-mappath-method.md, iis/web-development-reference/native-code-api-reference/iprotocolmanager-getpminterface-method.md, iis/web-development-reference/native-code-api-reference/iscriptmapinfo-getresourcetype-method.md, iis/web-development-reference/native-code-api-reference/isendresponseprovider-getlogdata-method.md, iis/wmi-provider/authenticationprovidersettings-class.md
This PR fixes 29 missing descriptions.
=> [Bulk] Validation: validation fixes JM 5/24a

iis/extensions/smooth-streaming-client/chunkinfo-compareto-method-microsoft-web-media-smoothstreaming_1.md, iis/web-development-reference/native-code-api-reference/cglobalmodule-terminate-method.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onupdaterequestcache-method.md, iis/web-development-reference/native-code-api-reference/iapphostcollectionschema-clearelementschema-property.md, iis/web-development-reference/native-code-api-reference/iapphostelementschema-iscollectiondefault-property.md, iis/web-development-reference/native-code-api-reference/iapphostelementschema-name-property.md, iis/web-development-reference/native-code-api-reference/ihttpapplication-getapplicationid-method.md, iis/web-development-reference/native-code-api-reference/ihttpcompletioninfo-getcompletionbytes-method.md, iis/web-development-reference/native-code-api-reference/ihttpconnectionstoredcontext-interface.md, iis/web-development-reference/native-code-api-reference/ihttpcontext-gettracecontext-method.md, iis/web-development-reference/native-code-api-reference/ihttptokenentry-getprimarytoken-method.md, iis/web-development-reference/native-code-api-reference/ihttpuser-getuservariable-method.md, iis/web-development-reference/native-code-api-reference/imetadatainfo-getvrtoken-method.md, iis/web-development-reference/native-code-api-reference/imoduleallocator-allocatememory-method.md, iis/web-development-reference/native-code-api-reference/imoduleallocator-interface.md, iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-deleterawcollectionelement-method.md, iis/web-development-reference/native-code-api-reference/ipmhealthandidlemonitor-interface.md, iis/web-development-reference/native-code-api-reference/iprotocolmanager-interface.md, iis/web-development-reference/native-code-api-reference/ireadentityprovider-setentity-method.md, iis/web-development-reference/native-code-api-reference/isendresponseprovider-setlogdata-method.md
This PR fixes about 20 missing descriptions.
=> [Bulk] Validation: fix missing descriptions

iis/extensions/database-manager-reference/databaseinfo-properties-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/typeinfo-defaultscale-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/view-methods-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/adaptivesource-adaptivesourcestatusupdatedevent-event.md, iis/extensions/smooth-streaming-client/cacheresponse-constructor-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/iadaptivesource-manifest-property.md, iis/extensions/smooth-streaming-client/iis-smooth-streaming-client-1-5.md, iis/extensions/smooth-streaming-client/manifeststream-maxheight-property.md, iis/extensions/smooth-streaming-client/manifeststream-name-property.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalvideoheightproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-supportedplaybackrates-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streaminfo-parentstream-property-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-streamupdatedevents-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-disabletracedestination-method-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackinfo-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/transform-manager/imonitoringservice-deletejob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-assetretentionperioddisplayunit-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdetails-jobdetailsinstancefilename-field-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobmanifest-template-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/logger-dispose-method-boolean-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/transformmanagerservice-getrunningjobs-method-microsoft-web-media-transformmanager.md, iis/wmi-provider/application-class.md, iis/wmi-provider/handlerssection-class.md, iis/wmi-provider/mapping-iis-6-0-wmi-methods-to-iis-7-and-higher-wmi-methods.md, iis/wmi-provider/workerprocesscontainsappdomain-class.md
This PR fixes 25 missing descriptions.
=> [Bulk] Validation: validation fixes JM 5/20a

iis/extensions/database-manager-reference/column-constructor-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbbackupmanager-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/idbtabledatamanager-insertrow-method-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/iis-database-manager.md, iis/extensions/database-manager-reference/index-properties-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/querycolumnmetadata-constructor-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/storedprocedure-properties-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/adaptivesourcemanagerfailedeventargs-class.md, iis/extensions/smooth-streaming-client/cache-plug-in-implementation-of-ismoothstreamingcache.md, iis/extensions/smooth-streaming-client/chunkinfo-stream-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/clipinformation-constructor-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/cookies-property.md, iis/extensions/smooth-streaming-client/iadaptivesourcemanager-adaptivesourcemanagerfailedevent-event.md, iis/extensions/smooth-streaming-client/ihttpcookie-p3ppolicy-property.md, iis/extensions/smooth-streaming-client/imanifeststream-displaywidth-property.md, iis/extensions/smooth-streaming-client/protectionheader-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-attributes-property-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-volumeproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-methods-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/tracing-tracehistorymaxlines-field-microsoft-web-media-diagnostics_1.md, iis/extensions/smooth-streaming-client/trackinfo-endgetchunk-method-microsoft-web-media-smoothstreaming.md, iis/extensions/transform-manager/jobdefinition-logfolder-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobdefinition-maintenanceintervalminutes-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/manifestproperty-properties-microsoft-web-media-transformmanager.md, iis/wmi-provider/applicationpool-start-method.md, iis/wmi-provider/applicationpoolelementdefaults-class.md, iis/wmi-provider/cachingprofilesettings-class.md, iis/wmi-provider/devicefilterssection-class.md, iis/wmi-provider/traceareaelement-class.md, iis/wmi-provider/verbssettings-class.md
This PR fixes 29 missing descriptions.
=> [Bulk] Validation: bulk validation fixes JM 5/20

iis/extensions/smooth-streaming-management-rest-services/incomingfragmentwaittime-element.md, iis/extensions/smooth-streaming-manifest-structure/iis-smooth-streaming-client-manifest-protectionheader-element.md, iis/extensions/transform-manager/configurationbase-addconfigurationmessage-method-string-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/cglobalmodule-onglobalapplicationresolvemodules-method.md, iis/web-development-reference/native-code-api-reference/cglobalmodule-onglobalcachecleanup-method.md, iis/web-development-reference/native-code-api-reference/chttpmodule-onpostpreexecuterequesthandler-method.md, iis/web-development-reference/native-code-api-reference/iapphostconfigexception-configpath-property.md, iis/web-development-reference/native-code-api-reference/iapphostconfigexception-linenumber-property.md, iis/web-development-reference/native-code-api-reference/icustomnotificationprovider-querynotificationtype-method.md, iis/web-development-reference/native-code-api-reference/ihttpcachepolicy-isusercacheenabled-method.md, iis/web-development-reference/native-code-api-reference/ihttpcachepolicy-setvarybyvalue-method.md, iis/web-development-reference/native-code-api-reference/ihttpconnectionstoredcontext-notifydisconnect.md, iis/web-development-reference/native-code-api-reference/ihttpmoduleregistrationinfo-setrequestnotifications-method.md, iis/web-development-reference/native-code-api-reference/ihttprequest-deleteheader-method.md, iis/web-development-reference/native-code-api-reference/ihttprequest-sethttpmethod-method.md, iis/web-development-reference/native-code-api-reference/ihttpresponse-flush-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver-getapppoolname-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver-readfragmentfromcache-method.md, iis/web-development-reference/native-code-api-reference/ihttpuser-supportsisinrole-method.md, iis/web-development-reference/native-code-api-reference/iprebeginrequestprovider-gethttpcontext-method.md, iis/web-development-reference/native-code-api-reference/iprebeginrequestprovider-interface.md, iis/web-development-reference/native-code-api-reference/iprocesshost-enumerateappdomains-method.md, iis/web-development-reference/native-code-api-reference/iscriptmapinfo-interface.md, iis/web-development-reference/native-code-api-reference/iwpflistenerchannelcallback-getblob-method.md
This PR fixes about 24 missing descriptions.
=> [Bulk] Validation: fixing descrip missing-cc1

iis/extensions/smooth-streaming-client/clipinformation-properties-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/protectionheader-constructor-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-flushbuffers-method-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/traceentry-properties-microsoft-web-media-diagnostics.md, iis/extensions/smooth-streaming-management-rest-services/enumerate-web-site-publishing-points.md, iis/extensions/transform-manager/jobdefinition-nodetaskcodepathx86-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/jobscheduler-schedulertype-property-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/localscheduler-cleanupjob-method-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskdetails-structure-microsoft-web-media-transformmanager.md, iis/extensions/transform-manager/taskstatus-settaskchildprocessid-method-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/chttpmodule-chttpmodule-method_1.md, iis/web-development-reference/native-code-api-reference/icustomactionresultcallback-interface.md, iis/web-development-reference/native-code-api-reference/iglobaltraceeventprovider-checksubscription-method.md, iis/web-development-reference/native-code-api-reference/ihttpapplication2-queryiswarmingup-method.md, iis/web-development-reference/native-code-api-reference/ihttpcompletioninfo2-interface.md, iis/web-development-reference/native-code-api-reference/ihttprequest-gethttpmethod-method.md, iis/web-development-reference/native-code-api-reference/ihttprequest-getremoteaddress-method.md, iis/web-development-reference/native-code-api-reference/ihttpresponse-getkernelcacheenabled-method.md, iis/web-development-reference/native-code-api-reference/ihttpserver-recycleprocess-method.md, iis/web-development-reference/native-code-api-reference/ihttpuser-getpassword-method.md, iis/web-development-reference/native-code-api-reference/inativeconfigurationelementcollection-getrawelementbyindex-method.md, iis/web-development-reference/native-code-api-reference/initcompression-function.md, iis/web-development-reference/native-code-api-reference/iprocesshostsupportfunctions-getapphostconfigfilename-method.md, iis/web-development-reference/native-code-api-reference/iprocesspingcallback-respond-method.md, iis/web-development-reference/native-code-api-reference/iwpflistenerchannelcallback-reportstopped-method.md
This PR fixes about 25 missing descriptions.
=> [Bulk] Validation: Fixing missing descriptions

iis/configuration/administrators/index.md, iis/configuration/administrators/managementScope/add.md, iis/configuration/administrators/managementScope/index.md, iis/configuration/administratorsProviders/add.md, iis/configuration/administratorsProviders/index.md
This PR makes minor tweaks for the same description over 5 articles.
=> [Bulk] Validation: Fix dupe descriptions

iis/application-frameworks/building-and-running-aspnet-applications/aspnet-technical-resources.md, iis/application-frameworks/building-and-running-aspnet-applications/how-to-capture-aspnet-page-trace-events-in-iis-tracing.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/b2evolution-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/coppermine-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/crafty-syntax-live-help-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/cubecart-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/expressionengine-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/gallery2-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/geeklog-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/install-drupal-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/install-wordpress-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/limesurvey-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/mambo-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/mediawiki-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/openads-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/phplist-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/phpnuke-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/phpwcms-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/pmachinepro-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/siteframe-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/using-fastcgi-to-host-php-applications-on-iis.md, iis/application-frameworks/install-and-configure-php-applications-on-iis/xoops-on-iis.md, iis/application-frameworks/install-and-configure-php-on-iis/enable-per-site-php-configuration-on-iis-60-and-iis-7-and-above.md, iis/application-frameworks/install-and-configure-php-on-iis/install-and-configure-mysql-for-php-applications-on-iis-7-and-above.md, iis/application-frameworks/install-and-configure-php-on-iis/install-the-sql-server-driver-for-php.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-php-with-configuration-settings.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-your-infrastructure-and-php-applications.md, iis/application-frameworks/install-and-configure-php-on-iis/secure-your-sql-server-database.md, iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/classic-asp-parent-paths-are-disabled-by-default.md, iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/using-classic-asp-with-microsoft-access-databases-on-iis.md
Fixed broken links in iis-docs.
=> [BrokenLinksH2] Fixed broken links

iis/extensions/url-rewrite-module/enabling-pretty-permalinks-in-wordpress.md
Updates the link to the official "How to install WordPress" instructions.
=> Update link to WordPress install instructions.

iis/docfx.json
This PR is to fix issues related to build validation messages.
=> Validation issues | 2 (BULK)

iis/docfx.json, iis/extensions/database-manager-reference/dependenciesmissingexception-constructor-microsoft-web-management-databasemanager_1.md, iis/extensions/database-manager-reference/dependenciesmissingexception-constructor-serializationinfo-streamingcontext-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/queryresult-columnmetadata-property-microsoft-web-management-databasemanager.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentsegmentindexproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-currentsegmentindexproperty-field-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalvideoheightproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/smoothstreamingmediaelement-naturalvideowidthproperty-field-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedeventargs-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-class-microsoft-web-media-smoothstreaming.md, iis/extensions/smooth-streaming-client/streamupdatedlisteventargs-class-microsoft-web-media-smoothstreaming_1.md, iis/extensions/smooth-streaming-management-rest-services/autorestartonencoderreconnect-element.md, iis/extensions/transform-manager/configurationbase-configurationdirectory-property-microsoft-web-media-transformmanager.md, iis/web-development-reference/native-code-api-reference/iwpfapplicationinfoutil-interface.md, iis/web-development-reference/native-code-api-reference/pfn-webhost-listener-application-created-function.md
This PR is to fix issues related to build validation messages.
=> Validation issues | 1 (BULK)

iis/extensions/troubleshooting-application-request-routing/troubleshooting-502-errors-in-arr.md, iis/extensions/web-playlists/iplaylistrequestinfo-getservervariable-method.md, iis/get-started/whats-new-in-iis-10-version-1809/new-features-introduced-in-iis-10-1809.md, iis/install/installing-iis-85/installing-iis-85-on-windows-server-2012-r2.md
This PR fixes 28 validation issues.
=> [Bulk] Validation - Various fixes

iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/customAuthentication/providers/add.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/customAuthentication/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/customAuthentication/providers/add.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/customAuthorization/index.md, iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/customAuthorization/provider.md, iis/contribute.md, iis/get-started/whats-new-in-iis-8/iis-80-websocket-protocol-support.md, iis/manage/powershell/an-introduction-to-windows-powershell-and-iis.md, iis/media/web-playlists/web-playlists-for-iis-configuration.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
**DO NOT MERGE THIS PULL REQUEST WHILE IN DRAFT STATUS!** Some of the changes to links and other content are not valid until after go-live.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: …
=> [BULK UPDATE] DocuTune - Rebranding links

iis/application-frameworks/install-and-configure-php-on-iis/install-the-sql-server-driver-for-php.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck
=> [BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

iis/get-started/whats-new-in-iis-10-version-1809/new-features-introduced-in-iis-10-1809.md
This Pull Request was generated automatically as part of a global effort to improve metadata quality. Please review and merge this Pull Request within 5 days. If you have any questions or concerns about these metadata updates, please contact docs-allowlist-mgmt@microsoft.com. If you are not the correct contact for this content and repository, please notify Metadata-Management@microsoft.com.
Fixing[#619571 Remove ms.technology value iis](https://dev.azure.com/ceapex/Content%20Learning%20Content%20Architecture/_workitems/edit/619571)
If this Pull Request is not merged within 14 days, it will be automatically merged by our system to ensure the timeliness of the metadata update.Please notify Metadata-Management@microsoft.com if you would like Pull Requests for metadata updates to merge …
=> [METADATA UPDATE] Global metadata changes

iis/application-frameworks/install-and-configure-php-applications-on-iis/install-oscommerce-on-iis.md
Line 24: Updated download link.
=> [BrokenLinksH2]

iis/publish/using-web-deploy/export-a-package-through-iis-manager.md
=> [BrokenLinksH2] - Deletion of broken links

iis/application-frameworks/scenario-build-a-php-website-on-iis/configuring-step-1-install-iis-and-php.md
Installing php via the Web Platform installer is no longer possible.
=> WebPI is no longer available

iis/extensions/database-manager-reference/index-methods-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/query-class-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/queryresult-columnmetadata-property-microsoft-web-management-databasemanager.md, iis/extensions/database-manager-reference/storedprocedure-methods-microsoft-web-management-databasemanager.md
This PR addresses the issue description-missing.
There are build warnings, but we were instructed not to fix duplicate title or H1 issues.
=> Validation: Multiple fixes 

samples/snippets/cpp/VS_Snippets_IIS/IIS7/IHttpResponseWriteEntityChunkByReference/cpp/I7traceErr.h, samples/snippets/cpp/VS_Snippets_IIS/IIS7/_MapPath/cpp/I7traceErr.h, samples/snippets/cpp/VS_Snippets_IIS/IIS7/_RaiseEvnt/cpp/I7traceErr.h, samples/snippets/cpp/VS_Snippets_IIS/IIS7/_ReadEntity/cpp/I7traceErr.h
Fixes the following Policheck issues:
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109133
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109138
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109144
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109145
=> Policheck Update - Aug 30 | Bulk Update

iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe.md, iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe/samples/sample81.cmd
The paragraph was mistakenly moved to the plus code sample. Now move it back.
=> Fixed appcmd collection deletion sample.

iis/develop/windows-web-application-gallery/wordpress-sample-files.md
https://learn.microsoft.com/en-us/iis/develop/windows-web-application-gallery/wordpress-sample-files 
https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/develop/windows-web-application-gallery/wordpress-sample-files.md 
#PingMSFTDocs
=>  Typo "Wordpress"→"WordPress"

.openpublishing.redirection.json, iis/index.yml
[Review URL](https://review.learn.microsoft.com/en-us/iis/?branch=pr-en-us-991)
=> Landing page

iis/extensions/url-rewrite-module/modifying-http-response-headers.md
Fixed the typo as requested in #1003.
=> Fixed #1003.

iis/extensions/url-rewrite-module/url-rewrite-module-20-configuration-reference.md
Added missing doc about pattern attributes. Text taken from [URL Rewrite Module Configuration Reference](https://github.com/MicrosoftDocs/iis-docs/blob/main/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference.md#rule-conditions)
=> Add missing text

iis/TOC.yml, iis/web-dev-reference/server-variables.md
Reverts MicrosoftDocs/iis-docs#1059
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/33026
=> Revert "Remove dead content"

iis/publish/using-web-deploy/web-deploy-automatic-backups.md
Typo fix.  "he" corrected to "they".
Customer pointed out the unintentional "he", corrected to inclusive "they".
=> Minor: Typo fix "he" to "they" Update web-deploy-automatic-backups.md

samples/snippets/cpp/VS_Snippets_IIS/IIS7/IHttpRequestGetHeader/cpp/IHttpRequestGetHeader.cpp
Reverts MicrosoftDocs/iis-docs#1099
=> Revert "merge to live"

samples/snippets/cpp/VS_Snippets_IIS/IIS7/IHttpRequestGetHeader/cpp/IHttpRequestGetHeader.cpp
Reverts MicrosoftDocs/iis-docs#1100
=> Revert "Revert "merge to live""

iis/docfx.json
Adding ms.update-cycle setting in docfx.json to reflect tier level support.
Contributes to dotnet/aspnetcore.docs#35962
=> Update docfx.json with ms.update-cycle setting
