iis/configuration/system.webServer/applicationInitialization/index/samples/sample1.xml

The `applicationInitialization` element should not be closed, since `add` is a child of that element.

Fixed invalid xml

---

iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference.md

REQUEST_URI starts with slash (/). I updated the example in documentation and added line about PATH_INFO.
Added trailing dots in 2 places.

Fix REQUEST_URI description, add PATH_INFO example

---

iis/configuration/system.applicationHost/sites/site/application/index.md

Based on the IIS Configuration Schema, the correct attribute name should be 'preloadEnabled' instead of 'preLoadEnabled'.
The attribute name is case-sensitive and will result in error.

Updated attribute preLoadEnabled to preloadEnabled

---

iis/manage/configuring-security/application-pool-identities/samples/sample2.cmd

The cmd in file results on a windows server 2016 to an `Invalid parameter "IIS AppPool\DefaultAppPool"`. See also https://serverfault.com/questions/385604

Fix quotation mark position

---

iis/manage/configuring-security/understanding-iis-url-authorization.md
iis/manage/configuring-security/understanding-iis-url-authorization/samples/sample7.xml

This is an update to my former pull request #107.
Here is the original text:
> As can be seen here: https://msdn.microsoft.com/en-us/library/wce3kxhd.aspx
> 
> "Anonymous users are identified using a question mark (?). You can specify all authenticated users using an asterisk (*)."
I created a new pull request which is now based on the current state of the repository (includes newer recent commits) and updates the document following a comment by @bariscaglar .
Sorry for creating a new PR, I would have updated the old one, but I had created it without downloading the repo and just using Github's online editing tools. While this worked, I wasn't able to update it like I normally would (then again, it's been ages since I submitted a pull request).

Correct errors on anymous vs authenticated

---

iis/publish/troubleshooting-web-deploy/web-deploy-error-codes.md

The documentation mentions for a couple of issues that the appOffline rule can be implemented, but then fails to provide a link to how to implement this rule, and the provided GUI for publish profiles do not include this setting. I found the much referred to, first google search result for `azure app service appoffline rule` on StackOverflow and put it into this document

howto implement appOffline rule included

---

iis/develop/runtime-extensibility/developing-iis-modules-and-handlers-with-the-net-framework.md

The correct FQN is System.Web.IHttpAsyncHandler
https://msdn.microsoft.com/en-us/library/system.web.ihttpasynchandler(v=vs.110).aspx

Fix misspelled interface name

---

iis/configuration/system.ftpServer/security/authentication/denyByFailure.md

@shirhatti @bangbingsyb Would you review this IIS doc update? This is for adding missing information for FTP Logon Attempt Restriction feature. 
If client's ip matches to an existing static IP "allow" rule only for server level and only for a single IP address rule, FTP Logon Attempt Restriction check is being skipped.

Fixed #199

---

iis/web-dev-reference/server-variables.md

This is for the new server variable REQUEST_FLAGS which was added in RS5.
REQUEST_FLAGS can be used to determine which HTTP protocol is used.
https://github.com/MicrosoftDocs/iis-docs/issues/291

REQUEST_FLAGS added

---

iis/extensions/url-rewrite-module/reverse-proxy-with-url-rewrite-v2-and-application-request-routing.md

change warning to match other repos in docs
example= https://github.com/MicrosoftDocs/vsts-docs/blob/82443ee23b7ebde53f409d8686a3800a6ecff9ee/docs/organizations/public/migration-checklist.md

add warning markdown

---

iis/docfx.json

I think we should not have the engine switch in the middle of the MSDN migration. After the CAPS content is merged, we can have @cillroy to run the markdig migration report for us to see potential issues in addition to the whacky path warnings we were getting.

switch markdown engine

---

iis/configuration/system.webServer/httpRedirect/index.md

`marking.contoso.com` should be `marketing.contoso.com`

Fix typo in `childOnly` sample code

---

iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage.md

The IISLogCleaner.exe download link location has changed.
Fixing Issue: https://github.com/MicrosoftDocs/feedback/issues/2450

Correcting the IISLogCleaner download link

---

iis/troubleshoot/performance-issues/troubleshooting-iis-performance-issues-or-application-errors-using-logparser.md

fix:  Remove trailing brace in literal links

---

.markdownlint.json
iis/publish/troubleshooting-web-deploy/web-deploy-error-codes.md

Fenced code blocks should be surrounded by blank lines

fix: MD031/blanks-around-fences

---

.markdownlint.json
iis/configuration/system.applicationHost/index.md
iis/configuration/system.ftpServer/index.md

Headings must start at the beginning of the line

fix: MD023/heading-start-left/header-start-left

---

.github/CODEOWNERS

codeowners doesn't work across orgs. Would this be the right team? We can also assign individual reviewers

Fix team org

---

iis/publish/using-the-ftp-service/configuring-ftp-user-isolation-in-iis-7.md

After converting to Markdown, `/%` becomes `%`, so such must be manually fixed.

Fixed broken directory syntax.

---

iis/manage/remote-administration/remote-administration-for-iis-manager/samples/sample3.cmd

Because sc is an alias for Set-Content in PowerShell, you need to write sc.exe

Change sc to sc.exe in sample command

---

iis/configuration/system.webServer/httpErrors/error.md

It is not obvious that some error codes cannot be customized when that piece of information is solely in https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753103(v=ws.10)
By replicating the same note here, it can save customers some time.

Added a note.

---

iis/get-started/introduction-to-iis/introduction-to-iis-architecture.md

The phrase "HTTP Protocol" is redundant, as HTTP means "Hypertext Transfer Protocol".

Remove redundant "protocol" after "HTTP"

---

iis/extensions/url-rewrite-module/using-the-url-rewrite-module.md

Fix the download link for the URL rewrite module. The previous links went to installers that were not compatible with current versions of IIS. The download from the IIS extension home page should be better supported than direct links to a specific version of the module.
This PR should also fix #305.

Fix download link for the URL rewrite module

---

iis/web-development-reference/native-code-api-reference/TOC.yml
iis/web-development-reference/native-code-api-reference/loadmanagedruntime-function.md
iis/web-development-reference/native-code-api-reference/loadmanagedruntimeex-function.md
iis/web-development-reference/native-code-api-reference/native-code-architecture-api-reference.md

For APIScan compliance.
Please check TOC placement, IIS versions, header file.
[Preview link](https://review.docs.microsoft.com/en-us/iis/web-development-reference/native-code-api-reference/loadmanagedruntime-function?branch=pr-en-us-546).

Add docs for LoadManagedRuntime

---

iis/develop/windows-web-application-gallery/azure-app-gallery-faq.md
iis/develop/windows-web-application-gallery/blogengine-net-sample-files.md
iis/develop/windows-web-application-gallery/database-notes-for-packaging-applications-for-use-with-the-web-application-gallery.md
iis/develop/windows-web-application-gallery/frequently-asked-questions.md
iis/develop/windows-web-application-gallery/gallery-server-pro-sample-files.md
iis/develop/windows-web-application-gallery/how-to-create-an-app-package-supporting-both-sql-server-and-mysql.md
iis/develop/windows-web-application-gallery/integrate-the-windows-web-application-gallery-into-a-control-panel.md
iis/develop/windows-web-application-gallery/introducing-the-windows-web-application-gallery.md
iis/develop/windows-web-application-gallery/joomla-sample-files.md
iis/develop/windows-web-application-gallery/mediawiki-sample-files.md
iis/develop/windows-web-application-gallery/package-an-application-for-the-windows-web-application-gallery.md
iis/develop/windows-web-application-gallery/reference-for-the-web-application-package.md
iis/develop/windows-web-application-gallery/testing-a-web-application-zip-package-for-inclusion-with-the-web-application-gallery.md
iis/develop/windows-web-application-gallery/umbraco-cms-sample-files.md
iis/develop/windows-web-application-gallery/using-the-microsoft-web-platform-installer-badge.md
iis/develop/windows-web-application-gallery/windows-web-application-gallery-known-issues.md
iis/develop/windows-web-application-gallery/windows-web-application-gallery-link-addition-process-walkthrough.md
iis/develop/windows-web-application-gallery/windows-web-application-gallery-principles.md
iis/develop/windows-web-application-gallery/wordpress-sample-files.md

With my last PR I placed the blurb above the H1, which is not permitted.  (refer failures in the [Build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5C90f071cf-c002-b629-5e11-5bc968bb67ca%5CPullRequest%5C202104221931287959-556%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F0CPhmfGWgnbhYsAHGlq7RCWktueQ5oAm%2FPWWfwlr8I%3D&st=2021-04-22T19%3A27%3A44Z&se=2021-05-23T19%3A32%3A44Z&sp=r))
This PR moves the blurb below the H1.

Move WWAG retirement blurb

---

iis/publish/deploying-application-packages/dotnetnuke.md

Given that the DotNetNuke installation environment that is supported with deployment through the Web Platform Installer or the Web Matrix installation is an older, not-current, installation version this update makes two notes to this documentation.
1. References added to the DNN Community site which is the proper documentation for all DNN Platform (Open Source) information
2. Added a callout/quote note to draw attention to the need to upgrade after installation to the latest version of DNN, with an included link to the instructions on that upgrade process.
If this is not a proper method to make this recommended change, please let me know.  I just wanted to make sure it was noted that the installation versions as outlined in this guide SHOULD NOT be used in production without upgrades.

Updated DotNetNuke Documentation References

---

iis/configuration/system.webServer/globalModules/index.md

Fixed four lines (lines 63, 66, 69, and 98) for missing alttext. Added descriptions for images.

iis-docs-reemedit

---

iis/extensions/url-rewrite-module/reverse-proxy-with-url-rewrite-v2-and-application-request-routing.md

In the ...1. Expand the conditions group box... section there is a second backslash close to the end of the example Pattern (but not on the screenshots) and what makes the example not working as described.
So
5. In the "Pattern" textbox enter "**^/(webmail|payroll)/.\\***".
probably should be
5. In the "Pattern" textbox enter "**^/(webmail|payroll)/.\*".
Best regards.

Condition pattern example failure

---

iis/configuration/system.applicationHost/applicationPools/add/environmentVariables/add.md
iis/configuration/system.applicationHost/applicationPools/applicationPoolDefaults/environmentVariables/add.md
iis/configuration/system.applicationHost/sites/site/ftpServer/connections.md
iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/basicAuthentication.md
iis/configuration/system.applicationHost/sites/site/ftpServer/security/authentication/index.md
iis/configuration/system.applicationHost/sites/site/ftpServer/security/commandFiltering/index.md
iis/configuration/system.applicationHost/sites/site/ftpServer/security/sslClientCertificates.md
iis/configuration/system.applicationHost/sites/site/ftpServer/sessions/index.md
iis/configuration/system.applicationHost/sites/site/ftpServer/sessions/session.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/connections.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/basicAuthentication.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/authentication/index.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/commandFiltering/index.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/security/sslClientCertificates.md
iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md
iis/develop/runtime-extensibility/developing-a-module-using-net.md
iis/extensions/url-rewrite-module/request-blocking-rule-template.md
iis/extensions/url-rewrite-module/user-friendly-url-rule-template.md
iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-1709-hsts.md
iis/get-started/whats-new-in-iis-10-version-1709/new-features-introduced-in-iis-10-1709.md
iis/get-started/whats-new-in-iis-10/iisadministration-powershell-cmdlets.md
iis/media/live-smooth-streaming-events/behind-the-scenes-with-silverlight-and-iis-at-the-2010-winter-games-in-vancouver-editor39s-cut.md
iis/media/live-smooth-streaming-events/behind-the-scenes-with-silverlight-and-iis-at-the-2010-winter-games-in-vancouver-highlights.md
iis/overview/powerful-admin-tools.md
iis/publish/using-the-ftp-service/adding-ftp-publishing-to-a-web-site-in-iis-7.md
iis/publish/using-the-ftp-service/configure-ftp-with-iis-manager-authentication-in-iis-7.md
iis/publish/using-the-ftp-service/configuring-ftp-user-isolation-in-iis-7.md
iis/publish/using-the-ftp-service/configuring-ftp-with-net-membership-authentication-in-iis-7.md
iis/publish/using-webdav/how-to-configure-webdav-settings-using-appcmd.md
iis/publish/using-webdav/how-to-configure-webdav-with-request-filtering.md

Duplicate-descriptions and preserve-view-not-set fixes.

Validation: Duplicate-descriptions and preserve-view-not-set fixes.

---

iis/publish/using-the-ftp-service/adding-ftp-publishing-to-a-web-site-in-iis-7.md

**Global effort to fix broken links**
@rmcmurray
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!
I've been unable to locate the x86 download anywhere on a Microsoft site.

[BrokenLinksH2] fixing broken links

---

iis/troubleshoot/diagnosing-http-errors/how-to-use-http-detailed-errors-in-iis.md
iis/troubleshoot/security-issues/troubleshooting-forms-authentication.md

I corrected a couple of instances where the "fix" was incomplete, by removing all link coding from example URLs. This should be ready for merge.

[BrokenLinksH2] broken link fix QA

---

iis/application-frameworks/running-php-applications-on-iis/mix08-partying-with-php-on-microsoft-internet-information-services-7-and-above.md

**Global effort to fix broken links**
@Rick-Anderson
@mcleblanc
The C+E Skilling team is fixing broken links on learn.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

[BrokenLinksH2]

---

iis/develop/runtime-extensibility/develop-a-native-cc-module-for-iis.md

The IIS 7 SDK Reference page doesn't seem to exist any more. Link to the native code development overview instead.

Revised the link to fix #526.

---

iis/publish/troubleshooting-web-deploy/troubleshooting-common-problems-with-web-deploy.md

The case study section is too long, so break it into smaller sections.
The error messages by Visual Studio are also grouped into code blocks, so that readers can easily distinguish them from other contents.
| 📄 File | 🔗 Preview link |
|:--|:--|
| _iis/publish/troubleshooting-web-deploy/troubleshooting-common-problems-with-web-deploy.md_ | [Preview: iis/publish/troubleshooting-web-deploy/troubleshooting-common-problems-with-web-deploy](https://review.learn.microsoft.com/en-us/dotnet/iis/publish/troubleshooting-web-deploy/troubleshooting-common-problems-with-web-deploy?branch=pr-en-us-978) |

Split case study to sections and grouped messages.

---

iis/extensions/introduction-to-iis-express/iis-express-overview.md

* The most recent release is now IIS 10 Express, not IIS 7.5 Express. As IIS 7.x reached end of life a long while ago, IIS 7.5 Express is likely to be deprecated as well.
* Visual Studio 2008, Web Platform Installer, and WebMatrix are end of life, so removed references about them.
* Removed deprecated Windows releases and added newer Windows releases.
* While VS 2010 and 2012 reached end of life, VS 2010 SP1 was the very first release to enable built-in IIS Express, so leave it in the article just for reference.

Update this page to remove deprecated references.

---

iis/docfx.json

This content is missing an L2 header, which is a required element. This PR adds uhfHeaderId to docfx file so that this content uses the Windows L2 header. If you feel that this content should use an L2 header other than Windows, please reply with a comment indicating which header it should use instead. Thank you! For more information see: https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main
@mcleblanc @Rick-Anderson Please review, thanks!

Use Windows L2 header

---

iis/manage/provisioning-and-managing-iis/managing-iis-log-file-storage.md

Removed third party cleaner tool, which is no longer available.
This should address the concerns in #995.

Update managing-iis-log-file-storage.md to fix #995

---

iis/breadcrumb/toc.yml
iis/docfx.json

This PR brings breadcrumb implementation into alignment with [platform architecture requirements](https://review.learn.microsoft.com/en-us/help/platform/navigation-overview?branch=main#requirements-for-content-ecosystems). This PR is part of a previously announced batch of breadcrumb fixes across the Learn platform and will be auto-merged if there are no build warnings. This PR may include removing the “extend breadcrumb” feature from any docfx files that are still using it, fixing breadcrumb file references in the docfx file, and rewriting breadcrumb files to match the [approved breadcrumb pattern](https://review.learn.microsoft.com/en-us/help/platform/navigation-breadcrumbs-overview?branch=main#breadcrumbs-in-documentation) for a given product’s documentation.

Fix breadcrumbs

---

iis/configuration/system.webServer/httpRedirect/index.md

Instead of renaming to the correct number of codes ("four") I would suggest removing it entirely so this isn't missed when a new one comes along.

Remove incorrect count

---

iis/configuration/system.webServer/httpLogging.md

All the below examples have dontLog set to true which means IIS won't log requests.
https://learn.microsoft.com/en-us/iis/configuration/system.webserver/httplogging#sample-code

Fix httpLogging example desc. for dontLog=true

---

iis/configuration/system.applicationHost/sites/site/ftpServer/userIsolation/index.md
iis/configuration/system.applicationHost/sites/siteDefaults/ftpServer/userIsolation/index.md
iis/publish/using-the-ftp-service/configuring-ftp-user-isolation-in-iis-7.md
iis/web-hosting/configuring-servers-in-the-windows-web-platform/guide-to-deploy-ftp-and-publish-with-vwd.md

Show hidden path separators.
It's fine for plain text, but it was hidden in Markdown.

fix hidden path separators

---

iis/publish/using-the-ftp-service/configuring-ftp-firewall-settings-in-iis-7.md

Settings like passive port range require a service restart to take effect. Without such hints, users just don't know why their changes didn't work. There have been tons of previous threads on different online forums, so hope this change can avoid more in the future.

Add a hint on restarting FTP service

---

iis/get-started/planning-your-iis-architecture/deep-dive-into-iis-configuration-with-iis-7-and-iis-8.md

The main problem here is that `The content of is a list of sections` is missing a word. The content of what? 
configSections is always written starting with a lowercase c.
Coincidentally, I noticed this issue in the documentation today when I read through it, and then I saw @Rick-Anderson just left a review on someone else's PR (https://github.com/MicrosoftDocs/iis-docs/pull/929) to fix this issue. That's an old PR and I'm not sure if the guy who created it is still active. So here's my proposed changes.

improve clarity of configSections docs in Deep Dive into IIS Config page

---

iis/get-started/planning-for-security/build-a-custom-iis-server.md

"The ASP.NET page handler is a good example." on its own after just giving an example of a IIS module is misleading and out of place. Added a few words to clarify that we're moving on to talking about handlers.

Clarify misleading example of an IIS handler

---

iis/get-started/planning-your-iis-architecture/deep-dive-into-iis-configuration-with-iis-7-and-iis-8.md
iis/get-started/planning-your-iis-architecture/deep-dive-into-iis-configuration-with-iis-7-and-iis-8/samples/sample8.xml

I'm not sure how this `<span>` element got here, since obviously there are no span elements in the IIS config. I'm assuming it has something to do with the fact that these are old articles and they probably got converted into markdown after they were originally created.

Fix IIS config sample by changing from HTML to XML

---

iis/manage/configuring-security/using-encryption-to-protect-passwords/samples/sample5.cmd

https://learn.microsoft.com/iis/manage/configuring-security/using-encryption-to-protect-passwords
Based on the source code of `createProvider.exe` showed in this article, when its input is `iisWasKey RsaKeyForWAS Rsa_WAS`, it should add a provider in `machine.config` whose name is `Rsa_WAS`, with keyContainerName `iisWasKey` and description `RsaKeyForWAS`. However, the element in the old sample file didn't match.
Besides, the sample file should have showed enough context of all three provider items, so I chose to expand the contents to the entire `configProtectedData` tag. In this way, the `defaultProvider` attribute modified by `setProvider.exe` is also showed.
What this pull request doesn't include is the hint that how x86/x64 and .NET Framework 4.0+ scenarios should be handled, because …

Update sample5.cmd to match test results

---

iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference.md

The background can be found in https://learn.microsoft.com/en-us/answers/questions/2243039/how-to-select-308-for-a-redirect-in-iis-10-url-rew
It seems that IIS 10 added HTTP status code 308 support in HTTP Redirect, in [IIS_Schema.xml](https://github.com/lextm/iis_schema/commit/2a639ef765f9ec6f40248762618ca8528c9d199b). However, URL Rewrite module wasn't updated accordingly.
This pull request adds a note in URL Rewrite documentation to point that out. Whether HTTP status code 308 should be supported by URL Rewrite module future releases is to be determined by the product owner.
@Rick-Anderson

Added a note on HTTP status code 308

---

iis/configuration/system.webServer/httpCompression/index.md

Update to how elements and attributes of httpCompression work.

Update to httpCompression attributes
